### ISSUE TITLE
Предлагаю улучшить музыкальную часть сборки 

### ISSUE THREAD

**Issue by Yorodoshi** [TerraFirmaGreg-Team/Modpack-1.20.x#103]
### Версия используемого модпака

0.1.2

### Связанная проблема

Пластинки надо постоянно перевтыкать когда они заканчиваются и это в целом не так уж и удобно.

### Ваше решение

Music Player [1.20.1]  или иной мод на музыку внутри игры

### Дополнительная информация

Много нудного фарма нуждаются в музыкальном сопровождении

**Comment by SpeeeDCraft** [comment]
Я не понимаю в чем полезность мода, если можно просто в браузере запустить музыку и сидеть слушать. Или с этим модом люди в радиусе смогут слышать то, что у тебя включено?

**Comment by Yorodoshi** [comment]
> Я не понимаю в чем полезность мода, если можно просто в браузере запустить музыку и сидеть слушать. Или с этим модом люди в радиусе смогут слышать то, что у тебя включено?

В браузере это не то ) Хочется чтоб всё и сразу было в майнкрафте, тот же JEI, рецепты тоже же можно посмотреть на вики.

**Comment by SpeeeDCraft** [comment]
Сделал
