### ISSUE TITLE
Интеграция Pollution of the Realms

### ISSUE THREAD

**Issue by Thomasx0** [TerraFirmaGreg-Team/Modpack-1.20.x#144]
### Версия используемого модпака

1.20

### Ваше решение

Доброго дня. Считаю т.к мир технический стоит добавить этот моды. 
https://www.curseforge.com/minecraft/mc-mods/advanced-chimneys

https://www.curseforge.com/minecraft/mc-mods/pollution-of-the-realms

Игрок должен следить за уровнем загрязнения окружающей среды от всех машинок которые он использует. Также добавит больше взаимодействия с газами которые выделяются в процессе работы. Придется продумывать вентиляцию на базе.

**Comment by slava110** [comment]
Какой мод на печки?
