### ISSUE TITLE
Fire Clay, Tin alloy and Wood Gear

### ISSUE THREAD

**Issue by sevenninesixthree** [TerraFirmaGreg-Team/Modpack-1.20.x#169]
### Your Question

How can I get fire clay, tin alloy and wood gear? I have searched on JEI carefully but seems that crafting any of them is impossible.

**Comment by SpeeeDCraft** [comment]
Fire clay:
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/52341158/9e55f448-4716-49ae-86ab-8eca3fda8139)

Wood gear:
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/52341158/6529eddf-8c58-4bc6-9720-8ae14a3d263f)

Tin Alloy:
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/52341158/cadf22fa-187b-4cbd-afc7-7fa728652d5f)

**Comment by EmperialDev** [comment]
I think the author means you can't craft fire clay, because you can't craft graphite powder since it requires graphite dust, which you can't craft without steam machines (which requires steel).

I think the author wihes for a recipe that doesn't require steam machines for the wood gears (wood plate requires compressor).

You need tin alloy to make an alloy smelter however you can't make tin alloy outside the alloy smelter. (Mabye add it to tfc alloying?).

**Comment by Faduty** [comment]
Yeah. Same problem I found today. It is not possible to make tin alloy for small pipes, you need an alloy smelter or a steam forging hammer, both of which require small tin alloy pipes. Fire clay is broken. And the wooden gears are also broken.

**Comment by SpeeeDCraft** [comment]
Why fire clay recipe is broken? I dont understand really. Dig graphite -> Get Raw Ore -> Make Dust -> Use quern -> Graphite powder. Kaolinite clay (Just find it in the world)

**Comment by SpeeeDCraft** [comment]
> I think the author means you can't craft fire clay, because you can't craft graphite powder since it requires graphite dust, which you can't craft without steam machines (which requires steel).
> 
> I think the author wihes for a recipe that doesn't require steam machines for the wood gears (wood plate requires compressor).
> 
> You need tin alloy to make an alloy smelter however you can't make tin alloy outside the alloy smelter. (Mabye add it to tfc alloying?).

u can wash the ore in water, all the recipes are in jei

**Comment by SpeeeDCraft** [comment]
ok, wood gear recipe is really broken

**Comment by SpeeeDCraft** [comment]
Fixed tin alloy, red alloy, redstone, wood gear recipes

**Comment by chemlzh** [comment]
@SpeeeDCraft How to make dust from raw graphite, or wash raw graphite? I use REI to show recipes ,which shows that raw graphite cannot be washed, and only crushed ore can. However, crushed graphite needs GT steam power or Create crushing wheels, both of which are higher-tier tech. The only way to obtain graphite dust is to smelt graphite ore with Create encased fans and lava, but how can I find a lava source, put the fan and smelt ores safely?

**Comment by EmperialDev** [comment]
@chemlzh you can break graphite ore with a hammer and get crushed graphite ore.

**Comment by chemlzh** [comment]
> @chemlzh you can break graphite ore with a hammer and get crushed graphite ore.

Sorry to bother you, but REI shows that raw graphite (include poor/rich) doesn't have the crushing recipe which uses hammer. The version of TFG:NH is 0.6.6, so I don't know what had happened.

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/91b9e00a-7a20-4252-84b1-c39a4897220d)

**Comment by EmperialDev** [comment]
@chemlzh you need to break the graphite ore block in-world with a hammer to get crushed graphite ore.

**Comment by chemlzh** [comment]
> @chemlzh you need to break the graphite ore block in-world with a hammer to get crushed graphite ore.

OK, thanks! It works! Since I'm not familiar with GT, I have not realized this approach. Thanks a lot!

**Comment by Kecuxa** [comment]
Dear god, i searching info for the graphite ore in the TFC book and in all quests. Can u add description on crushing ore "break ore with a hammer to get crushed ore in the early stages"?

**Comment by WaterMelwin** [comment]
Learn to read quests

**Comment by Jordanb716** [comment]
I just found this trying to solve the issue myself. The quests page doesn't explain this. It starts the graphite branch with crushed graphite, but has no explanation on how to make it. Also seems very strange that there's no recipe to just use a hammer to convert already collected graphite into crushed graphite.

**Comment by WaterMelwin** [comment]
> I just found this trying to solve the issue myself. The quests page doesn't explain this. It starts the graphite branch with crushed graphite, but has no explanation on how to make it. Also seems very strange that there's no recipe to just use a hammer to convert already collected graphite into crushed graphite.

wow quests literally tell you what to do
