### ISSUE TITLE
Ошибка в крафте

### ISSUE THREAD

**Issue by Maximnety** [TerraFirmaGreg-Team/Modpack-1.20.x#177]
### Версия модпака.

0.4.3

### Среда запуска

Одиночная игра

### Новые миры

Да

### Ожидаемое поведение

Крафт водолазных ботинок из медных ботинок

### Фактическое поведение

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/84129980/a222c2fc-6beb-4db3-bb80-206bd273afcc)
Водолазные ботинки крафтятся из медного шлема

### Действия по воспроизведению

Посмотрел в джей рецепт

**Comment by FriendlyCube** [comment]
всё норм , это замысел автора

**Comment by FriendlyCube** [comment]
а с водолазным шлемом все норм?

**Comment by Maximnety** [comment]
Да
