### ISSUE TITLE
инструменты и слитки  сервер 0,5,1

### ISSUE THREAD

**Issue by LisiGoblin** [TerraFirmaGreg-Team/Modpack-1.20.x#181]
### Версия модпака.

0.5.1

### Среда запуска

сервер

### Новые миры

Не уверен

### Ожидаемое поведение

1. кирка и шахтерский  молот добывают руду
2. из слитков золота и меди можно хоть чтото скрафтить

### Фактическое поведение

1. Кирка и шахтерский  молот ничего не добывают
2. из слитков золота и меди ничего не крафтится

### Действия по воспроизведению

1.1 Скрафтить кирку/шахтерский молот
1.2 найти то что хотите сломать
1.3 сломав ничего не получить
2.1 иметь при себе слитки золота или меди из тфк

### Дополнительная информация

https://youtu.be/YrblEfqi7PI Видео с демострацией

**Comment by SpeeeDCraft** [comment]
Все работает верно, на счет того, что не работают инструменты, говори спасибо грегтеху, придется пересоздавать мир, если в локалке, то перенеси вещи креативом и пробелем не будет. Слитки используются из GT и ваниллы, тфкшные были отключены вот и превратились в картошку, возьми себе такие же только из ваниллы/гт из креатива и будет тебе счастье
