### ISSUE TITLE
Tin alloy plates are unobtainable before LV machines

### ISSUE THREAD

**Issue by Wyrmlet** [TerraFirmaGreg-Team/Modpack-1.20.x#183]
### Version modpack Used

0.5.1

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

Tin alloy ingots can be forged into plates.

### Actual Behavior

Tin alloy ingots can only be forged into rods.
![20240113_15h46m20s_grim](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/19237631/ccad110f-3194-4a17-a4a9-529f9d9584c5)

### Steps to Reproduce

Launch a new world, attempt to forge a tin alloy ingot.

### Additional Information

This also makes tin alloy pipes unobtainable without cheats, which breaks progression in survival. I also cannot put tin alloy ingots into a crucible to smelt them, which might be related.

**Comment by SpeeeDCraft** [comment]
make sense, thanks for report

**Comment by SpeeeDCraft** [comment]
fixed
