### ISSUE TITLE
Coke brick mold consumed when crafting coke bricks

### ISSUE THREAD

**Issue by Wyrmlet** [TerraFirmaGreg-Team/Modpack-1.20.x#186]
### Version modpack Used

0.5.1

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

When creating coke oven bricks, the mold is not consumed, allowing for crafting those in bulk.

### Actual Behavior

When creating coke oven bricks, the mold is consumed.

### Steps to Reproduce

Attempt to craft coke oven bricks.

### Additional Information

From what I've seen this is not how this works in other packs, so this feels like a bug to me. In any case, the mold disappearing doesn't make much sense, especially since those don't stack, so each individual brick needs to be made manually.

**Comment by SpeeeDCraft** [comment]
Thanks for report, this has been done because gtceu had bug with that shit, but now it fixed and we can back to original behavior
