### ISSUE TITLE
Bread recipe consumes too much yeast starter from barrels

### ISSUE THREAD

**Issue by Wyrmlet** [TerraFirmaGreg-Team/Modpack-1.20.x#187]
### Version modpack Used

0.5.1

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

When using a barrel as a container for yeast starter in the bread recipe, only one bucket is consumed per craft.

### Actual Behavior

When using a barrel in this recipe, the whole barrel is emptied for one craft.

### Steps to Reproduce

Attempt to craft terrafirmalife bread with a barrel of yeast starter that is more  than 1 bucket full.

**Comment by SpeeeDCraft** [comment]
Fixed by firmalife dev, I assume
