### ISSUE TITLE
Terrafirmalife greenhouses need TFC rods instead of gregtech rods

### ISSUE THREAD

**Issue by Wyrmlet** [TerraFirmaGreg-Team/Modpack-1.20.x#188]
### Version modpack Used

0.6.2

### Environment

Singleplayer

### New Worlds

Unsure

### Expected Behavior

Greenhouse blocks are craftable.

### Actual Behavior

Greenhouse blocks are not craftable, as the recipe requires TFC rods which have no recipe.
![20240116_17h58m06s_grim](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/19237631/08b1e12e-cdde-4b16-b939-7fde1b4aaa7d)

### Steps to Reproduce

Try to craft a greenhouse wall with copper or iron.

**Comment by SpeeeDCraft** [comment]
Thanks for report

**Comment by SpeeeDCraft** [comment]
Fixed
