### ISSUE TITLE
Не работает рецепт на пиле из Create

### ISSUE THREAD

**Issue by Faduty** [TerraFirmaGreg-Team/Modpack-1.20.x#193]
### Версия модпака.

0.6.2 - 0.6.3

### Среда запуска

Синглплеер, мультиплеер, локальный сервер

### Новые миры

Да

### Ожидаемое поведение

Создание деревянных пластин на циркулярной пиле из Крейта

### Фактическое поведение

Деревянные пластины из Грега не делаются на циркулярной пиле из Крейта, вместо них сломанный тэг. А аналогичный рецепт из пропитанных досок - делается.
![111](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/88941613/4c7e7825-cfce-4a76-8beb-244c44b80fe5)
![222](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/88941613/ab21fe86-d61e-46e9-a4ba-3dd063c1f2c2)

### Действия по воспроизведению

Просто глянуть рецепт

### Дополнительная информация

Я пробовал перезагрузки скриптов, текстур и тд, не помогает

**Comment by SpeeeDCraft** [comment]
Этих рецептов вообще не должно быть, удалил крч
