### ISSUE TITLE
Невозможно апгрейднуть пояс из ToolBelt (Фиксить будем миксинами)

### ISSUE THREAD

**Issue by Mwyah** [TerraFirmaGreg-Team/Modpack-1.20.x#194]
### Версия модпака.

0.6.3

### Среда запуска

Игра по локальной сети

### Новые миры

Да

### Ожидаемое поведение

Ожидается крафт
![EtNqBGiNMBY](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/72641087/976f35c7-8ac9-4971-8519-12414773e2a2)

### Фактическое поведение

Крафт отсутствует. Если попытаться выставить рецепт через плюсик около рецепта, то карман для пояса переносится в окно крафта, а пояс - нет.
![gbDwoI-KQ3g](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/72641087/3cfab2e3-e18a-4f9a-bdc0-94edb4df6b89)

### Действия по воспроизведению

Выложить рецепт в верстаке (пояс без улучшений).

**Comment by SpeeeDCraft** [comment]
Короче разраб дебил, я хз как это править, только если разблокировать ванильную наковальню, но у нас как бы она запрещена, короче мод удалим и возможно в будущем переработаем
