### ISSUE TITLE
Нет рецепта массового плавления для рудного золота

### ISSUE THREAD

**Issue by TDumpling** [TerraFirmaGreg-Team/Modpack-1.20.x#198]
### Версия модпака.

0.6.3

### Среда запуска

одиночная игра

### Новые миры

Да

### Ожидаемое поведение

Переплавка рудного золота(среднего) в золотой слиток по аналогии с богатым и бедным кусками руды
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/42238325/3f590157-5f66-4415-bf0d-52de78736db5)
Богатое:
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/42238325/244512cc-3cfc-4677-97bb-84b0e077e8d8)
Бедное:
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/42238325/5af92434-73e8-40ed-b81b-c1e4526d8761)

### Фактическое поведение

Руда не плавится, просто исчезает
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/42238325/634b9be9-7108-4e6b-b244-ec2090902fcc)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/42238325/a72d57c4-6b21-4d97-b941-226f07363475)

### Действия по воспроизведению

Попробовать переплавить рудное золото с помощью лавы и вентилятора

**Comment by TDumpling** [comment]
upd: для обычной плавки в печи также нет рецепта

**Comment by SpeeeDCraft** [comment]
Исправлено, спасибо, что зарепортили
