### ISSUE TITLE
Конфликтующие крафты компаса

### ISSUE THREAD

**Issue by TDumpling** [TerraFirmaGreg-Team/Modpack-1.20.x#199]
### Версия модпака.

0.6.3

### Среда запуска

одиночная игра

### Новые миры

Да

### Ожидаемое поведение

Компас можно скрафтить на верстаке

### Фактическое поведение

Конфликтующие крафты обычного компаса и компаса указывающего на север(из firma: civilization) не дают скрафтить компас на верстаке. Всегда получается именно компас из firma: civilization. Компас нужен для спидометра, стрессометра и жд станции из create
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/42238325/caa4acbc-bb9f-40e6-96e5-2cbdc5b988ed)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/42238325/ac162f36-0c01-4b95-b12e-6c6c9cca8bd2)

### Действия по воспроизведению

Попытаться скрафтить компас
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/42238325/c17d39f6-24ba-45c1-92b0-7d265119c58d)

### Дополнительная информация

Можно просто добавить перекрафт из одного компаса в другой

**Comment by SpeeeDCraft** [comment]
Спасибо, что сообщили, удалим все рецепты ванильного компаса и вставим везде из FirmaCiv.

**Comment by DIVIner-Sai** [comment]
Энивей крафт не работает если крафтить в машине

**Comment by Exzept1on** [comment]
ты интересно где проверил, на 0.7.14, а я говорю про 0.8.0?
