### ISSUE TITLE
Crash on making plates with mechanical press

### ISSUE THREAD

**Issue by Wyrmlet** [TerraFirmaGreg-Team/Modpack-1.20.x#202]
### Version modpack Used

0.6.3

### Environment

Singleplayer

### Side Crashed

Server

### New Worlds

Unsure

### Steps to Reproduce

Using the mechanical press recipes for plates sometimes crashes the game. After the crash, the plate is not created, but the ingot is consumed.

### Crash Report

[crash-2024-01-19_18.45.01-server.txt](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/files/13986611/crash-2024-01-19_18.45.01-server.txt)
[latest.log](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/files/13986623/latest.log)

### Additional Information

This feels like a bug with the chance of no output in the recipe, as the plate is not created after the world is reloaded.

**Comment by Wyrmlet** [comment]
Tested on 0.6.6, an ingot was voided on the press but the game did not crash. Probably fixed.

**Comment by C0ffo** [comment]
У меня тоже что-то с пропажей под прессом,кинул под пресс листы делатся и когда через 5 мин пришел то их небыло нигде

**Comment by Wyrmlet** [comment]
Still happening as of 0.6.8, but not always. Sometimes plates are correctly voided, but sometimes the game crashes instead. Sometimes the plates are created after reloading, so maybe this is not connected to the chance output at all?
[crash-2024-01-25_14.01.02-server.txt](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/files/14046606/crash-2024-01-25_14.01.02-server.txt)
[latest.log](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/files/14046608/latest.log)

**Comment by SpeeeDCraft** [comment]
ok, thanks for report

**Comment by SpeeeDCraft** [comment]
Needs testing after 0.6.9, idk why this shit appers :(

**Comment by Wyrmlet** [comment]
From both server crash logs:
`java.lang.NullPointerException: Cannot assign field "locked" because "this.heldItem" is null`
Seems like it has something to do with the create depot logic and fails specifically if I don't have any item held? In any case, I ended up moving on to using a bender instead, so I'm not sure if I'll end up testing this as I play casually.

**Comment by Wyrmlet** [comment]
https://github.com/Creators-of-Create/Create/blob/2201d87da7744cf9ee3f83e1e4c21643244f342b/src/main/java/com/simibubi/create/content/logistics/depot/DepotBehaviour.java#L147

Looked through the relevant code, seems to be a create issue specifically? The tick update seems to lack a check for if the item held is null, and it tries to assign a value to it at line 147 regardless, which causes the null pointer exception. I'll try bringing this up in an issue on their github, maybe it'll get fixed on their end.

**Comment by Wyrmlet** [comment]
Started a new issue on https://github.com/Creators-of-Create/Create/issues/6053

**Comment by Wyrmlet** [comment]
According to the people in the create repo, this might be happening because mods for chunk claiming can interfere with how create works in some places. This needs to be tested with claimed chunks and without, as well as with and without the relevant mods. I did have my base claimed and chunkloaded, so that might have caused the issue.

**Comment by Wyrmlet** [comment]
For context, each time this happened I remember looking at the depot, it never happened while I was away. It also only seems to happen when my hands are empty. Hopefully this helps to verify this.

**Comment by SpeeeDCraft** [comment]
In any case, I assume that the crash is not related specifically to TerraFirmaGreg or its recipes, perhaps this is really an OpenClaims mod, in which case I will close it, we as modpack developers cannot fix it
