### ISSUE TITLE
Сломали крафт микросхем

### ISSUE THREAD

**Issue by a22kat** [TerraFirmaGreg-Team/Modpack-1.20.x#203]
### Версия модпака.

.6.5

### Среда запуска

сервер

### Новые миры

Да

### Ожидаемое поведение

Сломали крафт микросхем 
![Снимок экрана 2024-01-20 221832](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/60256920/ce6b1283-15f8-4fb0-aa62-a5a41de38a49)
![Снимок экрана 2024-01-20 221850](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/60256920/4c4c0ba3-158c-4b4d-8763-24ef40c330df)

### Фактическое поведение

-

### Действия по воспроизведению

-

**Comment by a22kat** [comment]
![Снимок экрана 2024-01-20 223056](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/60256920/01d65cc0-bb60-4893-a3c2-0b71f8b9a5f5)
Там много чего еще сломалось

**Comment by SpeeeDCraft** [comment]
Исправлено
