### ISSUE TITLE
Не выполняется квест на латекс

### ISSUE THREAD

**Issue by C0ffo** [TerraFirmaGreg-Team/Modpack-1.20.x#206]
### Version modpack Used

0.6.6

### Environment

Официальный сервер ТФГ

### New Worlds

Yes

### Expected Behavior

прошел бы квест с резиной и продолжил бы развитие

### Actual Behavior

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/151227314/02d9b3d6-21d2-4a9a-9a39-e18fa81b3ddb)
Резина должна тыкатся в квесте чтобы принятся но когда нажимаеш то ничего не происходит 

### Steps to Reproduce

Попробовать взять ведро с латексом и пройти тот квест

**Comment by SpeeeDCraft** [comment]
Fixed
