### ISSUE TITLE
The quest is not completed even though all conditions are met. Broken quest dependency.

### ISSUE THREAD

**Issue by Muphue** [TerraFirmaGreg-Team/Modpack-1.20.x#207]
### Version modpack Used

0.6.3

### Environment

Open to LAN

### New Worlds

Yes

### Expected Behavior

![image-9](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/126881708/00ea257e-a5c2-4170-9e95-aea15bfc5ffa)

### Actual Behavior

It should be done.

### Steps to Reproduce

Just do the quests

### Additional Information

The quest does not depend on the barrel. But it can't be done without it.

**Comment by SpeeeDCraft** [comment]
Fixed
