### ISSUE TITLE
Квест Battery Preparations!

### ISSUE THREAD

**Issue by a22kat** [TerraFirmaGreg-Team/Modpack-1.20.x#209]
### Версия модпака.

.6.8

### Среда запуска

сервер

### Новые миры

Да

### Ожидаемое поведение

Квест Battery Preparations! непроходим
![Снимок экрана 2024-01-24 140515](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/60256920/ecdeda8d-deb4-4f9f-929d-7ef7d142404f)

### Фактическое поведение

-

### Действия по воспроизведению

-

### Дополнительная информация

-

**Comment by SpeeeDCraft** [comment]
По прежнему, потому что и не исправляли

**Comment by a22kat** [comment]
Может их просто поудалять или сделать опциональными?

**Comment by SpeeeDCraft** [comment]
Fixed
