### ISSUE TITLE
Sterling silver dust recipe voltage tier mismatch

### ISSUE THREAD

**Issue by Wyrmlet** [TerraFirmaGreg-Team/Modpack-1.20.x#210]
### Version modpack Used

0.6.8

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

Sterling silver dust is craftable in an LV mixer.

### Actual Behavior

Sterling silver dust is only craftable in an MV mixer and above.
![20240126_10h25m48s_grim](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/19237631/5f760a83-8df4-4b7c-bd73-f35fd5477f49)

### Steps to Reproduce

Attempt to craft sterling silver using an LV mixer

### Additional Information

All the other TFC-related dusts are made in an LV mixer, so this doesn't make much sense.

**Comment by SpeeeDCraft** [comment]
funny

**Comment by SpeeeDCraft** [comment]
Fixed
