### ISSUE TITLE
Alternative crucible/fire clay recipe

### ISSUE THREAD

**Issue by Wyrmlet** [TerraFirmaGreg-Team/Modpack-1.20.x#211]
### Version modpack Used

0.6.8

### Related Problem

TFC crucibles are used in a few crafting recipes, notably you need them to make EBFs. Gathering kaolinite gets quite tedious.

### Your Solution

An alternative recipe for crucibles or fire clay, using more advanced materials that are easier to get later in the game. Maybe something that needs at least steam machines to make?

**Comment by Wyrmlet** [comment]
Made a mistake, EBFs need steam furnaces, not boilers, so they don't need crucibles. Still, it is a bit painful to make those in the steam age and LV when those are actually needed.

**Comment by EmperialDev** [comment]
Mabye also increase the chance to get kaolite powder from kaolin clay? Mabye increase it to 80% instead of 20%?

**Comment by sevenninesixthree** [comment]
Actually, you can put 64 kaolin clay in a small vessel, and then heat up it, in the crucible or anything you like. By doing this you can fire 64 kaolin clay at a time.

**Comment by SpeeeDCraft** [comment]
Fixed
