### ISSUE TITLE
Сломал блоки угля 

### ISSUE THREAD

**Issue by Neon4301** [TerraFirmaGreg-Team/Modpack-1.20.x#212]
### Версия модпака.

последняя

### Среда запуска

сервер

### Новые миры

Да

### Ожидаемое поведение

ожидаемо должно выпасть 8 кусочков угля 

### Фактическое поведение

![изображение_2024-01-28_215811652](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/89591462/f00c4b92-4926-470a-9bfe-1504b5e4827a)
вот такие кучки угля если сломать вот этим
![изображение_2024-01-28_215852386](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/89591462/79211851-e5c3-4118-9189-32c18dfcf8a8)
то выпадет всего 1 уголь вместо 8-ми

### Действия по воспроизведению

сломать этой лопатой 3х3х1 блок угля

**Comment by Wyrmlet** [comment]
I think I've encountered this too, both with 3x3 shovels and with drills. Never reported it as I didn't count the coal, so couldn't immediately tell it's bugged

**Comment by SpeeeDCraft** [comment]
Fixed

**Comment by SpeeeDCraft** [comment]
Ладно не исправлено, хз как это чудо править

**Comment by SpeeeDCraft** [comment]
Время писать разрабам грега

**Comment by SpeeeDCraft** [comment]
Ладно, шучу, починил сам, я же сильный
