### ISSUE TITLE
Нужно больше света

### ISSUE THREAD

**Issue by a22kat** [TerraFirmaGreg-Team/Modpack-1.20.x#213]
### Версия модпака.

.6.8

### Связанная проблема

У нас как бы индустриальная сборка, а из освещения факела да лампы всякие. Не индустриальненько как то.

### Ваше решение

Добавить какие ни будь лампы. На скорую руку нашел вот такой мод https://www.curseforge.com/minecraft/mc-mods/simply-light
Возможно есть какие ни будь другие варианты.

**Comment by SpeeeDCraft** [comment]
Сделай мод на лампы требующие электричество

**Comment by a22kat** [comment]
> Сделай

Чукча не читатель, чукча писатель :-) 

Тот мод кстати в рафтах использует глоустоун, так что лампы будут доступны только с ХВ.

**Comment by SpeeeDCraft** [comment]
У меня есть пару идей на этот счет, так что позже придумаем

**Comment by Exzept1on** [comment]
Установлен
