### ISSUE TITLE
Crash on launching world after update

### ISSUE THREAD

**Issue by Wyrmlet** [TerraFirmaGreg-Team/Modpack-1.20.x#215]
### Version modpack Used

0.6.10

### Environment

Singleplayer

### Side Crashed

Server

### New Worlds

Unsure

### Steps to Reproduce

Launch world.

### Crash Report

[crash-2024-02-01_22.08.30-server.txt](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/files/14125162/crash-2024-02-01_22.08.30-server.txt)
[latest.log](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/files/14125165/latest.log)

### Additional Information

Seems to be something related to create pipes? I have a bunch of those connected from a water source to some gregtech machines.
The world was initially on version 0.6.8, and this crash seems to have been caused by the update to 0.6.10.

**Comment by SpeeeDCraft** [comment]
GTCEu moment, cant help with that

**Comment by Wyrmlet** [comment]
I have removed all create pipes before update, then updated and rebuilt the pipes. Works well now.
