### ISSUE TITLE
Крафт Fluix block

### ISSUE THREAD

**Issue by a22kat** [TerraFirmaGreg-Team/Modpack-1.20.x#216]
### Версия модпака.

.6.10

### Среда запуска

сервер

### Новые миры

Да

### Ожидаемое поведение

Я конечно понимаю гринд, все дела, но это как то перебор. 
![Снимок экрана 2024-02-01 164746](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/60256920/d9f5f8fb-8b00-4893-8739-ae6707c8b514)
Для крафта оного блока 14 лямов кристалов ) 

### Фактическое поведение

![Снимок экрана 2024-02-01 175921](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/60256920/84ff1f94-1d62-4f62-9922-76c4e7e348a4)

### Действия по воспроизведению

-

**Comment by SpeeeDCraft** [comment]
Исправлено
