### ISSUE TITLE
Empty tags in pyrolyse oven recipes

### ISSUE THREAD

**Issue by Wyrmlet** [TerraFirmaGreg-Team/Modpack-1.20.x#217]
### Version modpack Used

0.6.8

### Environment

Singleplayer

### New Worlds

Unsure

### Expected Behavior

Pyrolyse oven can process logs into charcoal.

### Actual Behavior

The tag for burnable logs is empty, so the recipes are not functional.
![20240202_19h59m03s_grim](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/19237631/a4bf64f6-bd52-4336-96b7-9416c3edf1ac)

### Steps to Reproduce

Try using the pyrolyse oven with logs

**Comment by SpeeeDCraft** [comment]
Thanks for report. Fixed.
