### ISSUE TITLE
Лаги с шейдерами из за крейта

### ISSUE THREAD

**Issue by Redangys** [TerraFirmaGreg-Team/Modpack-1.20.x#219]
### Ваш вопрос

Можно ли как нибудь уменьшить радиус прогрузки определенных механизмов из крейта? До обновы если закрыть водяные колеса блоками то они не прогружались и не лагало, но теперь они грузятся сквозь блоки но на определенном расстояние. Как-нибудь можно поменять чтоб не грузились те же самые колеса водяные?
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/158020860/f2c10a7e-21e0-4cda-abc3-b7b40f0a17fa)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/158020860/9cfb68bd-0138-441d-a3f1-f14eac6af0c2)

**Comment by Redangys** [comment]
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/158020860/15eeadc4-f184-485c-8718-f8c226794490)
Если смотреть с расстояния то фпс хороший

**Comment by SpeeeDCraft** [comment]
Не представляю с чем может быть связано, эни вей множество оптимизаций не работают с Create, возможно из-за этого.

**Comment by Redangys** [comment]
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/158020860/bfb973bf-099a-42a3-af48-8ab7e00527e1)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/158020860/1689a455-28f2-4bdf-beec-b62bbd174764)
Сами колеса стоят на 46 высоте. т.е прогрузка идет где-то с 27-28 блоков.(Дополнил так как просто вот так оставить плохо будет)
