### ISSUE TITLE
Добавить возможность расплавки металических блоков теплицы

### ISSUE THREAD

**Issue by C0ffo** [TerraFirmaGreg-Team/Modpack-1.20.x#220]
### Version modpack Used

0.6.10

### Related Problem

Я наделал кучу железных плит которые выявились мне уже ненадобны,я хочу их расплавить но увы нельзя.
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/151227314/4678b8c1-e50f-4ba0-ad31-7be18c5ab26d)

### Your Solution

Добавить через Греговский дробитель,или доменую печь - плавку соотвественно затраченых ресурсов на блок
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/151227314/9c42c0fb-1d5e-4578-9f84-9d3fda5d50f9)
Железная/медная/нержавейка стена - 3 слитка (или порошка)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/151227314/9f81785a-2937-40ab-abaf-91bb59e4b10b)
Железная/медная/нержавейка крыша - 1,5 слитка (или 216 мб)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/151227314/078a7bdd-cf71-45fa-8c4c-25c6154efb51)
Железная/медная/нержавейка плита - так же 1,5 слитка (или 216 мб)

**Comment by SpeeeDCraft** [comment]
0.7.3
