### ISSUE TITLE
Gregicality rocketry blocks not craftable

### ISSUE THREAD

**Issue by Wyrmlet** [TerraFirmaGreg-Team/Modpack-1.20.x#221]
### Version modpack Used

0.6.10

### Environment

Singleplayer

### New Worlds

Unsure

### Expected Behavior

Gregicality rocketry blocks (like rocket engines, fuel tanks, launch pads, etc.) have a crafting recipe.

### Actual Behavior

A lot of gregicality rocketry blocks are not craftable.

### Steps to Reproduce

-

### Additional Information

This might be because the mod is not yet integrated with the rest of the pack, but a bunch of other items from the mod do have a recipe, so I decided to report just in case.

**Comment by SpeeeDCraft** [comment]
report to greg. rocketry git
