### ISSUE TITLE
Квесты: проблема триггера жидкой резины

### ISSUE THREAD

**Issue by Ckarlet** [TerraFirmaGreg-Team/Modpack-1.20.x#223]
### Version modpack Used

0.6.11

### Environment

Сервер

### New Worlds

Unsure

### Expected Behavior

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/159018816/2b13318e-1bfd-4f83-8fc8-cf1c5335ebe9)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/159018816/eae6f2a9-8545-497d-a4d0-2d6ce77cce1f)
В описание написана любая тара желательно бочка 
В бочке достаточно жидкой резины 

### Actual Behavior

Квест не засчитывается
Также пробовал универсальные капсулы

### Steps to Reproduce

воспроизвести условия выполнения как на скриншоте

**Comment by SpeeeDCraft** [comment]
Я уже СТО РАЗ писал о том, что квесты все еще не готовы, хватит мне репортить о их багах, в данный момент это не приоритетно
