### ISSUE TITLE
Flight options in midgame/lategame

### ISSUE THREAD

**Issue by Wyrmlet** [TerraFirmaGreg-Team/Modpack-1.20.x#225]
### Version modpack Used

0.6.11

### Related Problem

Building and exploring is slow at the beginning of the game because of the lack of movement options, which can get annoying later on.

### Your Solution

Add some kind of mod that allows for flight. Perhaps one of the many jetpack mods would work.

### Additional Information

Should probably be locked behind LV or MV.

**Comment by SpeeeDCraft** [comment]
When armor is added to GTCEu, then jetpacks will appear, but for now we will not do shit and add it from other mods.
