### ISSUE TITLE
Mining hammer only gives normal raw ores

### ISSUE THREAD

**Issue by EmperialDev** [TerraFirmaGreg-Team/Modpack-1.20.x#226]
### Version modpack Used

0.6.11

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

When mining ore blocks with mining hammer I expeted them to drop poor, normal and rich raw ores.

### Actual Behavior

When mining ore blocks only normal raw ores are dropped.

### Steps to Reproduce

Mine ore blocks with mining hammer.

**Comment by SpeeeDCraft** [comment]
Not a bug

**Comment by SpeeeDCraft** [comment]
stop, I'm a fool

**Comment by SpeeeDCraft** [comment]
thanks for report

**Comment by Redangys** [comment]
Еще шахтер добывает только обычную руду
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/158020860/9bd1152e-5d89-48ab-832a-d163192d1ef6)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/158020860/c233a707-14dc-48d7-801a-33bd1adc2938)

**Comment by SpeeeDCraft** [comment]
Fixed
