### ISSUE TITLE
Нет инструмента для ломания Cleat (Firma: Civilizations)

### ISSUE THREAD

**Issue by Mwyah** [TerraFirmaGreg-Team/Modpack-1.20.x#229]
### Версия модпака.

0.6.11

### Среда запуска

Официальный сервер

### Новые миры

Нет

### Ожидаемое поведение

Возможность сломать железячку (я хз, как cleat на русский перевели), например, киркой, чтобы иметь возможность её переставить.

### Фактическое поведение

Возможность тысячелетие колупать железячку любым инструментом, железячка не выпадает.

### Действия по воспроизведению

1) Поставить Cleat
2) Попытаться сломать
3)???
4)NO PROFIT

**Comment by SpeeeDCraft** [comment]
Исправлено, конечно же не разрабом мода, а мной, хи-хи, ха-ха
