### ISSUE TITLE
Генерация нефтеноского песка

### ISSUE THREAD

**Issue by KraftKraftKraft** [TerraFirmaGreg-Team/Modpack-1.20.x#230]
### Версия модпака.

6.11

### Среда запуска

Сервер

### Новые миры

Не уверен

### Ожидаемое поведение

Нефтеносный песок можно найти и добыть.

### Фактическое поведение

На сервере полно людей со сканерами которые обшарили огромную площадь но так и не нашли нефтеноского песка. По моему его просто нет. Ну или он настолько редкий что смысла его существования нет.

### Действия по воспроизведению

В одиночке не проверял могу посканить полетать.

**Comment by SpeeeDCraft** [comment]
Не везет, админ на Олеге находил его, так что терпим
