### ISSUE TITLE
Квест со стеклом в первой главе

### ISSUE THREAD

**Issue by InvisibleSpectator** [TerraFirmaGreg-Team/Modpack-1.20.x#231]
### Ваш вопрос

В оригинальной террафирме крафт стекла проходил с помощью обшитых латунью блоков, в сборке на смену им пришли латунные блоки из грега. Но рецепт получения латунных блоков требует минимум механизмов из Create с соответствующим количеством железа. Так задумано, что оригинальный рецепт террафирмы не был адаптирован под сборку, а усложнён для необходимости использовать Create, или это ошибка и стекло должно крафтиться только в рамках технологий террафирмы? 

Посмотрел крафт пресса, он требует в себя блок кованного железа, который для крафта себя требует пресс. Видимо всё же ошибка, либо все квесты первой главы со стеклом будут висеть до открытия нужных технологий.

Версия модпака 0.6.11

**Comment by SpeeeDCraft** [comment]
Блоки каолинитовой глины можно использовать вместо латунных
