### ISSUE TITLE
Крафт дамасской стали

### ISSUE THREAD

**Issue by Redangys** [TerraFirmaGreg-Team/Modpack-1.20.x#232]
### Версия модпака.

0.6.11

### Связанная проблема

Нету крафта дамасской стали ни одного, а по сути в МВ должен быть какой-то крафт

### Ваше решение

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/158020860/8cdeba7e-2171-4ea3-9448-664dcaff4f32)
Можно сделать крафт из стали так как формулы похожи. Допустим в той же электро доменной печи, сталь+1углерод и кислород в качестве газа. Ну как то так возможно.
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/158020860/52f79d17-3b81-4a44-84a9-a73c38984eec)

**Comment by Redangys** [comment]
Ну или можно в край упороться и сделать крафт только ручной из стали на наковальне. Чтоб патерн ковки был на грани ломания слитка, т.е почти невозможный(ну как если посчитать но тем не менее)

**Comment by SpeeeDCraft** [comment]
Зачем она тебе нужна? В греге нет для нее рецепта, напиши им на гит, пусть правят.

**Comment by Redangys** [comment]
В греге она только находится в данжах и т.п местах. А тут данжей нету. Значит и сталь не получить эту.
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/158020860/c06ab2d7-a1c8-46d1-a2ca-c57eb9620ed9)
А удача 3 на буре только на нем есть

**Comment by SpeeeDCraft** [comment]
Ну и хер с ней
