### ISSUE TITLE
Wrong production amount with multi-production ore

### ISSUE THREAD

**Issue by sevenninesixthree** [TerraFirmaGreg-Team/Modpack-1.20.x#234]
### Version modpack Used

0.6.11

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

multi-production common raw ore produce correct number of productions.(for example, smelting one raw redstone will get 5 redstone dust)

### Actual Behavior

multi-production common raw ore just produce one production.(for example,
smelting one raw redstone will just get one redstone dust.)

### Steps to Reproduce

1. open jei
2. search any multi-production ore(raw redstone)

**Comment by SpeeeDCraft** [comment]
True, thanks for report

**Comment by SpeeeDCraft** [comment]
GTCEu bug, waits for fix

**Comment by SpeeeDCraft** [comment]
Fixed
