### ISSUE TITLE
Ультрадюп железа

### ISSUE THREAD

**Issue by 8oyNextDoor** [TerraFirmaGreg-Team/Modpack-1.20.x#238]
### Версия модпака.

0.6.13

### Среда запуска

Одиночка и сервер

### Новые миры

Да

### Ожидаемое поведение

![javaw_AejNAcSXbO](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/130379681/96007772-0120-47f9-8b46-67fc7c9c7ef4)
1 пластина в 144 единиц железа в 1 дверь в 144 единиц

### Фактическое поведение

![javaw_DO8OE89FPm](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/130379681/d6523d7d-1338-4436-8c10-e9f3587e5d46)
Дверь плавится в 288 единиц...
![0DhL8B3nxP](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/130379681/ef1efe22-7a2f-4dd5-bee5-23ea3f1da910)
...и даёт 9 пыли + 1 самородок стали в дуговой

### Действия по воспроизведению

Глянуть рецепты железной двери

**Comment by SpeeeDCraft** [comment]
Исправлено
