### ISSUE TITLE
Слишком большое требование энергии на крафт сплава Rose Gold

### ISSUE THREAD

**Issue by Maxitanker** [TerraFirmaGreg-Team/Modpack-1.20.x#239]
### Версия модпака.

0.6.13

### Среда запуска

сервер

### Новые миры

Не уверен

### Ожидаемое поведение

Похожее потребление энергии и тир, как и у других похожих крафтов.

Пример:
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/47298638/0ac0130b-a390-4b83-ac35-6807be2efbae)

### Фактическое поведение

Крафт Rose Gold использует неадекватно много энергии и MV тир, хотя все остальные пыли цепочке цветной стали используют ULV
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/47298638/c02d4964-e3a0-48cc-a6aa-802cd4c721e5)

### Действия по воспроизведению

Положить в миксер (LV) медную и 4 золотые пфыли, выбрать 3 программу. Убедиться, что крафт не происходит

**Comment by Maxitanker** [comment]
А кастом крафт для пака не получится сделать? Буквально все пыли в цепочке - ULV тира, только эта штука MV.

**Comment by SpeeeDCraft** [comment]
Получится, но не приоритет, в след.патче скорее всего поправим, в какой раз уже приколы грега правим

**Comment by KraftKraftKraft** [comment]
Так это что типо баг что ли был?
А я думал фишка такая. МОл иди в тигеле плавь до мв, размечтался)

**Comment by SpeeeDCraft** [comment]
Исправлено
