### ISSUE TITLE
Рецепт каменной наковальни

### ISSUE THREAD

**Issue by z0the** [TerraFirmaGreg-Team/Modpack-1.20.x#243]
### Версия модпака.

0.6.14

### Связанная проблема

Не сразу понял как создать каменную наковальню, она так же не отображается как один из возможных "верстаков" для рецептов завязанных на наковальнях.
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/57135174/356663b6-1f8b-4fbd-bcca-00a286547a3e)

### Ваше решение

Было бы удобно если бы описание создания было сразу в квесте, без необходимости искать инфу в гайд-буке по TFC
![photo_2024-02-13_09-58-16](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/57135174/bbe1cb6c-6ae1-43c2-8ed7-0df9a2ed8c1c)

### Дополнительная информация

Дописать соответствующий квест

**Comment by FriendlyCube** [comment]
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/112543401/79d6a70e-581a-40b5-ad29-83608dbb6fbc)
