### ISSUE TITLE
Russian Quests

### ISSUE THREAD

**Issue by Alistair1231** [TerraFirmaGreg-Team/Modpack-1.20.x#245]
### Version modpack Used

0.6.14

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

Quests are expected to be English

### Actual Behavior

Quests are Russian

### Steps to Reproduce

1) Create World

### Additional Information

There might be more, but these are directly at the start of the modpack.
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/26165288/b3be5412-dbc2-48a5-b910-6eb0b1a8ea3d)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/26165288/bd6e4580-aa07-4a60-b193-4d04a899d16f)

**Comment by BabBimmaBome** [comment]
Crazy

**Comment by survivalmaster78** [comment]
english questbook coming out at release 1.0 if I recall correctly

**Comment by Alistair1231** [comment]
> english questbook coming out at release 1.0 if I recall correctly

Ah that makes sense. I really love what is there so far. I will take a break for the english version to mature some more, but I will definitely come back for this.
Never really player TFC or Gregtech before and really enjoying it so far. Never thought 5 hours of gameplay to finally get chests and a crafting table could be enjoyable, and the quests really helped guide me there. Though I still had to consult the book a lot.

**Comment by SpeeeDCraft** [comment]
Very strange, because, I'm translated a lot of quests, idk why it on Russian -_-

**Comment by SpeeeDCraft** [comment]
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/52341158/282c3f64-42ee-4acd-bc10-e249322d73c4)

using English (UK), I think problem on ur site, try to clear reinstall

**Comment by BabBimmaBome** [comment]
> ![image](https://private-user-images.githubusercontent.com/52341158/305000417-282c3f64-42ee-4acd-bc10-e249322d73c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTMxOTIsIm5iZiI6MTcwODAxMjg5MiwicGF0aCI6Ii81MjM0MTE1OC8zMDUwMDA0MTctMjgyYzNmNjQtNDJlZS00YWNkLWJjMTAtZTI0OTMyMmQ3M2M0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE2MDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MTI0ZTJmZTk4MGY4MzYxZTcwOTI1YzIxN2FkZTRiYjA0NzI0ODJkNWQ1ZGUwNjlhNjk0MDNkMzAyNmY1OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IZZEvsy8XI9GcWEPAPg8C5eE8-pAO-P0kxffaTUN8j0)
> 
> using English (US), I think problem on ur site, try to clear reinstall

not all are in english. I think this is all of them on the first quest page.
![javaw_2024-02-15_08-02-49](https://github.com/TerraFirmaGreg-Team/Modpa
![javaw_2024-02-15_08-06-18](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/84394057-c3b7-4bc3-a63e-38775ea43e6c)
![javaw_2024-02-15_08-07-18](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/bf295cc5-6d7a-4d05-a091-82c939c1b48a)
![javaw_2024-02-15_08-07-28](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/f38830c3-bafb-4fec-9db0-40ece5600086)


![javaw_2024-02-15_08-07-11](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/10120a4b-f453-4acd-a18a-024356d19ea8)

ck-1.20.x/assets/68994649/bd85ec5a-99cb-4aec-939b-6044a36f5104)
![javaw_2024-02-15_08-06-07](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/asset
![javaw_2024-02-15_08-06-45](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/a3ace8a9-b5fa-4ed9-b2a8-4fb5c9a55853)
s/68994649/0a19de43-2877-4616-8847-acc26d50fd85)

![javaw_2024-02-15_08-05-14](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/19bbe5bb-8a0f-43a4-9629-a082d5e6ddd1)
![javaw_2024-02-15_08-05-22](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994
![javaw_2024-02-15_08-05-48](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/f6457d9a-bcd5-44a9-b572-e374f13c108e)
649/46db147d-5a70-4236-b0b1-eb88ab9e4859)
![javaw_2024-02-15_08-05-54](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/29a615cb-b9dd-4fb8-a03f-6ce8cebc6173)

![javaw_2024-02-15_08-05-29](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/3fa98dca-e742-44e1-9eba-0644cfbaa2a3)

![javaw_2024-02-15_08-03-17](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/0a437ef8-c128-4059-be06-26ba28054491)
![javaw_2024-02-15_08-04-35](https://github.com/TerraFirmaGre
![javaw_2024-02-15_08-04-42](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/9fdd5806-87cf-4b2c-a925-2c2eab166bfc)
![javaw_2024-02-15_08-04-58](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/94e21bcf-a878-433d-ba51-12084683e3fa)

g-Team/Modpack-1.20.x/assets/68994649/bfa5fe42-e247-4fcc-9d76-be9418432657)

![javaw_2024-02-15_08-03-12](https://github.com/TerraFirmaGreg-Team/Modp
![javaw_2024-02-15_08-04-17](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/7e3481a9-2041-4306-b7ac-2c620bb6fbdf)
ack-1.20.x/assets/68994649/7dfe0f8b-3181-4f1d-96e1-1369489ddb2f)
![javaw_2024-02-15_08-03-39](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/bc463b37-9dfd-4b5c-8e04-017149535768)

**Comment by BabBimmaBome** [comment]
> ![image](https://private-user-images.githubusercontent.com/52341158/305000417-282c3f64-42ee-4acd-bc10-e249322d73c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMTMxOTIsIm5iZiI6MTcwODAxMjg5MiwicGF0aCI6Ii81MjM0MTE1OC8zMDUwMDA0MTctMjgyYzNmNjQtNDJlZS00YWNkLWJjMTAtZTI0OTMyMmQ3M2M0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDE2MDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0MTI0ZTJmZTk4MGY4MzYxZTcwOTI1YzIxN2FkZTRiYjA0NzI0ODJkNWQ1ZGUwNjlhNjk0MDNkMzAyNmY1OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IZZEvsy8XI9GcWEPAPg8C5eE8-pAO-P0kxffaTUN8j0)
> 
> using English (US), I think problem on ur site, try to clear reinstall

![javaw_2024-02-15_08-07-28](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/b518c1b7-c41c-4b8c-a845-3713782ccc4e)
![javaw_2024-02-15_08-02-49](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/d755a56d-e3c8-48fb-be64-66ff30e6e12c)
![javaw_2024-02-15_08-03-12](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/7f02ffcc-7696-4d45-86b4-743915b2cd53)
![javaw_2024-02-15_08-03-17](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/d6c75b97-43d8-479b-8761-feea61dbd08c)
![javaw_2024-02-15_08-03-39](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/19dbe944-9729-48b8-b5a0-ae6bb49191d6)
![javaw_2024-02-15_08-04-17](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/192fb1b8-464d-4dd1-b94a-d037a7993db1)
![javaw_2024-02-15_08-04-35](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/974670be-d834-4278-ac9f-404a6a09cc92)
![javaw_2024-02-15_08-06-07](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/9aba1a20-48ed-4dd5-b09f-5074058b7906)
![javaw_2024-02-15_08-06-18](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/910e2557-f62e-4b57-ae8b-44d66321c463)
![javaw_2024-02-15_08-06-45](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/e3fffb32-1afb-4d98-b51c-8b00d617e97b)
![javaw_2024-02-15_08-07-11](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/bb8c4f46-4097-4951-9a5d-5e7261d79e72)
![javaw_2024-02-15_08-07-18](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/086de7bf-caf8-4f0b-b3e8-0b75d34fe478)
![javaw_2024-02-15_08-04-58](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/b3410662-1d07-41b0-9cd3-4c78f30b3137)
![javaw_2024-02-15_08-04-42](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/3ceb8db9-f80a-430f-9cde-075c3eb90ac5)
![javaw_2024-02-15_08-05-14](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/b2b7d402-e3b7-481b-9dd6-b2d49064c99e)
![javaw_2024-02-15_08-05-22](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/9f718ffc-aa28-4fe1-8124-9ca51d75739a)
![javaw_2024-02-15_08-05-29](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/fef9b2d2-996d-4635-ab37-c12ce503fc41)
![javaw_2024-02-15_08-05-48](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/99845f54-42f3-48ee-8b9e-01b84db44f18)
![javaw_2024-02-15_08-05-54](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/68994649/7b237a75-b189-4a54-8208-a4d2a46fd976)
Not all are in English, I think this is all of them from page 1 of the quests.

**Comment by 0m3ga4** [comment]
I have the same issue, some quests are russian with english setting.

**Comment by BabBimmaBome** [comment]
yeah guess admin never realized I replied

**Comment by FriendlyCube** [comment]
0.о

**Comment by SpeeeDCraft** [comment]
Fixed!

**Comment by XyCrosier** [comment]
The quest about planks is still in Russian . Looks like you got all the rest though.
