### ISSUE TITLE
Добавление мода Immersive aircraft

### ISSUE THREAD

**Issue by Thomasx0** [TerraFirmaGreg-Team/Modpack-1.20.x#246]
### Версия модпака.

1.20

### Связанная проблема

В сборке мало более менее быстрых средств передвижения, а в мире грега и терры приходится часто бегать чтоб преодолевать большие расстояния.

### Ваше решение

Предлагаю добавить мод в сборку [Immersive aircraft](https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft). Позволяет создать несколько летательных аппаратов, дирижабли - грузовой и обычный, самолет, вертолет, и квадрокоптер. Можно органично вписать рецепты крафта под террафирму  и грег.

![изображение](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/153584223/a4538a2f-65fd-4dee-ad78-80376fae7904)

**Comment by SpeeeDCraft** [comment]
Да, мы ждем Create Aeronautics

**Comment by unazikx** [comment]
> Вот дождемся Create Aeronautics и будет нам и машины и дирижабли,самолеты и тд

нет не будет)) как минимум пока модпак не обновится до 1.21.1
[reference](https://github.com/TerraFirmaGreg-Team/Modpack-Modern/issues/3843#issuecomment-4275698965)
