### ISSUE TITLE
Невозможно скрафтить фотоальбом из Exposure

### ISSUE THREAD

**Issue by TDumpling** [TerraFirmaGreg-Team/Modpack-1.20.x#248]
### Версия модпака.

0.6.14

### Среда запуска

Одиночная игра, локальный сервер

### Новые миры

Да

### Ожидаемое поведение

Рецепт крафта с доступными компонентами

### Фактическое поведение

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/42238325/2f0b63ee-4977-4101-9e5e-f5f65aa6c5ec)
В рецепте есть мембрана фантома, которую невозможно получить

### Действия по воспроизведению

Ну типа

**Comment by SpeeeDCraft** [comment]
Исправлено, хоть и с опозданием на месяц
