### ISSUE TITLE
Food problems during winter (Primitive Age)

### ISSUE THREAD

**Issue by Nexuee** [TerraFirmaGreg-Team/Modpack-1.20.x#250]
### Version modpack Used

0.6.15

### Related Problem

During winter in the primitive age, access to food is much harder then access to water, thus causing the player to starve (which would be bad for people trying to play hardcore mode)

### Your Solution

I recommend adding a "Crook" Item, this item would be craftable with 3 sideways sticks in the 2x2 crafting grid. It would make it so leaves have a 10% chance to drop apples and thus help out greatly with the food problem and would spice up the diet from fish and meat and add atleast 1 part of variety

### Additional Information

the mod for this would be "Crooked Crooks" which adds crooks to the game :)

**Comment by Nexuee** [comment]
> ### Version modpack Used
> 0.6.15
> 
> ### Related Problem
> During winter in the primitive age, access to food is much harder then access to water, thus causing the player to starve (which would be bad for people trying to play hardcore mode)
> 
> ### Your Solution
> I recommend adding a "Crook" Item, this item would be craftable with 3 sideways sticks in the 2x2 crafting grid. It would make it so leaves have a 10% chance to drop apples and thus help out greatly with the food problem and would spice up the diet from fish and meat and add atleast 1 part of variety
> 
> ### Additional Information
> the mod for this would be "Crooked Crooks" which adds crooks to the game :)

![crook](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/160355050/66cceeae-3c6f-4b90-abec-53816bf31531)
The recipe could look like that :)

**Comment by EmperialDev** [comment]
Couldn't you just make a greenhouse? The hardest part is probably koalite clay for the glass and the compost takes some time to make, but you can still easily make it before winter.

**Comment by Nexuee** [comment]
> Couldn't you just make a greenhouse? The hardest part is probably koalite clay for the glass and the compost takes some time to make, but you can still easily make it before winter.

The main server is currently at winter so its very hard to find food, either by buffing animal spawns or adding new ways to get food its a large struggle

**Comment by gre4kapi** [comment]
just wait for summer, 1 day == 24 irl minutes

**Comment by SpeeeDCraft** [comment]
Use greenhouse for "winter" food, and wtf, spruce leaves drops apples, wHaT

**Comment by BabBimmaBome** [comment]
Can't make green house if you just joined lol xd
