### ISSUE TITLE
Изменить рецепт камеры из мода Exposure

### ISSUE THREAD

**Issue by gre4kapi** [TerraFirmaGreg-Team/Modpack-1.20.x#251]
### Версия модпака.

0.6.15

### Связанная проблема

Камеру нельзя скрафтить до МВ, так как в крафте используется линза из стекла, а она на лв делается только из изысканного хрусталя

### Ваше решение

Разрешить использовать в крафте любые линзы, например из других кристаллов (например рубин), которые можно добыть через просеиватель. Либо можно добавить в просеиватель аналогичный крафт для камней из стекла, как у других драг. камней

### Дополнительная информация
Также можно использовать в крафте lens (из которой компас и подзорная труба делается)

**Comment by FriendlyCube** [comment]
Можно добавить в крафт линзы, которые можно выдуть с помощью механики в тфк
