### ISSUE TITLE
Добавить рецепт починки для элитр

### ISSUE THREAD

**Issue by Redangys** [TerraFirmaGreg-Team/Modpack-1.20.x#252]
### Версия модпака.

последняя

### Связанная проблема

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/158020860/9b1d3213-023a-42fd-81e6-2f9e31e732ba)
Элитры очень быстро тратятся(пролетел буквально 5к блоков)

### Ваше решение

Рецепт для починки, ну или какой нибудь предмет чтобы они ремонтировались.... Мб их с зарядом сделать как у джетпака или тому подобного, чтобы вместо прочности тратилась энергия(можно добавить возможность апгрейда элитры хв батарейкой например)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/158020860/7e8dbfa0-086a-47c4-aebf-25ea9d8ddfa1)

**Comment by SpeeeDCraft** [comment]
Учитывая то, что их можно скрафтить (а не как в ванилле добыть), смысла в рецепте починки нет, совсем нет.
А на счет электро элитр, ты серьезно? Ты мод будешь писать на такое чудо?

**Comment by Redangys** [comment]
Они как расходник, таскать по 5-10 штук ну это много как минимум

**Comment by Redangys** [comment]
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/158020860/3ac7f86c-bf4e-4bb9-b911-faab72e32815)
Хотя бы рецепт починки с помощью составляющей

**Comment by SpeeeDCraft** [comment]
Я не помню, после того как элитры ломаются, они превращаются в сломанные элитры или просто пропадают?

**Comment by Redangys** [comment]
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/158020860/0bdf6f00-bb64-45ff-8225-b50974c4d8a4)
Они становятся вот такими и не используются

**Comment by Redangys** [comment]
надеть то можно а вот летать и т.д нет

**Comment by SpeeeDCraft** [comment]
Ладно, в таком случае можно, что-то придумать
