### ISSUE TITLE
Добавить Глайдер!

### ISSUE THREAD

**Issue by Floda28** [TerraFirmaGreg-Team/Modpack-1.20.x#254]
### Версия модпака.

Ласт

### Связанная проблема

Классная тема для перемещенная как минимум с горы

### Ваше решение

1)https://www.curseforge.com/minecraft/mc-mods/paragliders
2)https://www.curseforge.com/minecraft/mc-mods/hang-glider

**Comment by SpeeeDCraft** [comment]
Установлен

**Comment by Floda28** [comment]
🔥

Сб, 16 марта 2024 г. в 06:33, Dmitry ***@***.***>:
