### ISSUE TITLE
Измельчение огнеупорной глины

### ISSUE THREAD

**Issue by FieldmarshalDOOB** [TerraFirmaGreg-Team/Modpack-1.20.x#256]
### Версия модпака.

1.20.x

### Среда запуска

игра по локальной сети

### Новые миры

Да

### Ожидаемое поведение

Ожидается переработка созданной необоженной формы из огнеупорной глины в огнеупорную глину в измельчителе

### Фактическое поведение

Сборка необоженной формы из глины в измельчителе (не собирается)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/149330740/b243ac81-bac6-46a1-b84a-d098a010a85a)
![image3](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/149330740/7710dc0a-ca52-45f2-aa2d-bf84afb22e34)

### Действия по воспроизведению

Просмотр рецептов из необоженой огнеупорной глины 

### Дополнительная информация

Вероятно рецепт из сборщика

**Comment by SpeeeDCraft** [comment]
ахаха, косяк, исправим
