### ISSUE TITLE
Дюп стекла

### ISSUE THREAD

**Issue by TDumpling** [TerraFirmaGreg-Team/Modpack-1.20.x#259]
### Версия модпака.

0.6.15

### Среда запуска

Одиночная игра

### Новые миры

Да

### Ожидаемое поведение

В распиловке должна быть другая стеклянная панель
Не [gtceu:glass_plate], а [minecraft:glass_pane]
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/42238325/8a860492-ce3d-4616-bd2b-5deff1c70ee7)

### Фактическое поведение

Из цепочки рецептов (Распиловка блока на панели -> измельчение -> выплавка в блок в печи для сплавов) получается больше стекла чем было изначально

### Действия по воспроизведению

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/42238325/da7278e6-3679-4afe-a99f-14e6429dc284)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/42238325/f2ec12bf-5b6b-4d2d-b67e-bd67d5f9f679)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/42238325/19fa9f7a-cd98-4175-9dc4-04178b207e3a)

**Comment by KraftKraftKraft** [comment]
И это еще не самый вкусный дюп)
