### ISSUE TITLE
Create Deco mod добавление в сборку

### ISSUE THREAD

**Issue by ExpectoAmogus** [TerraFirmaGreg-Team/Modpack-1.20.x#263]
### Версия модпака.

0.6.15

### Ваше решение

Предложение добавить немного декора для заводов на сервере с этим модом [Create Deco](https://modrinth.com/mod/create-deco/version/kdQliEzD).

### Дополнительная информация

 Придется наверно поправить крафты и подчистить лишние материалы, поэтому я не настаиваю :)

**Comment by ExpectoAmogus** [comment]
в догонку еще один мод на рассмотрение [FramedBlocks](https://modrinth.com/mod/framedblocks) (Грубо говоря carpenter на 1.20)

**Comment by KraftKraftKraft** [comment]
Согласен. Декора не много. Я вот хотел какое то стекло разное и нашел только пару видов. Каленое стекло покрасить нельзя. Там в этих модах есть стекла?

**Comment by SpeeeDCraft** [comment]
Запланировано на 0.7.4
