### ISSUE TITLE
Не работает гаечный ключ

### ISSUE THREAD

**Issue by Tizer8** [TerraFirmaGreg-Team/Modpack-1.20.x#265]
### Версия модпака.

0.6.15

### Среда запуска

Сетевая, Клиент. 

### Новые миры

Не уверен

### Ожидаемое поведение

Возможность поворачивать генераторы и входные/выходные люки(проверено на них) через Shift + ПКМ. А так же создавать однонаправленные клапаны на трубах.

### Фактическое поведение

Ничего не происходит. На стороне держателя сервера всё работет.

### Действия по воспроизведению

1. Зайти на чужой сервер.
2. Попробовать повернуть  генератор.

### Дополнительная информация

На стороне держателя сервера всё работает, как и в одиночной игре.

**Comment by KraftKraftKraft** [comment]
У нас на серве работает. Присоединяйтесь)

**Comment by SpeeeDCraft** [comment]
Не могу воспроизвести, а даже если бы мог, то это была бы ошибка грега
