### ISSUE TITLE
[Question] Did something happen to the discord?

### ISSUE THREAD

**Issue by thedude3253** [TerraFirmaGreg-Team/Modpack-1.20.x#271]
### Your Question

All of the discord links I can find for TerraFirmaGreg are said to be invalid. Is there a more updated invite link? Did the server close down?

**Comment by iamrusskikh** [comment]
[TFG discord server invite link]( https://discord.gg/CHaEBekG)

**Comment by BabBimmaBome** [comment]
just means the links expired and need to be remade

**Comment by SpeeeDCraft** [comment]
Fixed, thanks for report

**Comment by iamrusskikh** [comment]
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/49066756/2a5dfd0e-bbf3-43ef-bb4b-110db804b62f)
Actually, fixed only on the team main page and wasn't in modpack repositories' readme.md files

**Comment by SpeeeDCraft** [comment]
Xikaro fixes this later
