### ISSUE TITLE
Рецепты в жёрнове

### ISSUE THREAD

**Issue by Iksanbro** [TerraFirmaGreg-Team/Modpack-1.20.x#275]
### Версия модпака.

0.6.15

### Связанная проблема

Многие крафты в жёрнове из Terrafirmacraft отсутствуют в других местах и занимают много времени без возможностей автоматизации. К примеру оливковую пасту можно сделать только в нём.

### Ваше решение

Добавление крафтов из жёрнова Terrafirmacraft в жёрнов и/или дробильные колёса из create и/или измельчитель из gregtech.

### Дополнительная информация

Так-же это достижимо если вернуть механизмы из Terrafirmacraft или созданием адаптера кинетики из create в Terrafirmacraft и наоборот.

**Comment by FriendlyCube** [comment]
можешь привести ещё примеры
