### ISSUE TITLE
[Bug] FTB tasks requiring liquid rubber and batteries cannot be submitted, and some description error on battery buffer

### ISSUE THREAD

**Issue by chemlzh** [TerraFirmaGreg-Team/Modpack-1.20.x#276]
### Version modpack Used

0.6.15

### Environment

Singleplayer

### New Worlds

No

### Expected Behavior

I have store the liquid rubber in the steel drum as quest requested. (See picture) Therefore it ought to allow me to submitted liquid rubber.

![2024-03-02_21 04 25](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/e9a7055f-b234-4cc4-9095-a9adb956e2b0)

![2024-03-02_21 11 31](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/ee3eed79-79c3-4a24-8ca6-59d5804d1d79)

(Updated on 2024.03.04)

I have found another bug about batteries. The task requires any kind of LV batteries, and I do have an uncharged sodium battery. Also, the previous task is done, so this task can be finished.

![2024-03-04_11 11 16](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/8420cbde-b75c-430d-ad66-ef549d3c2936)

![2024-03-04_11 11 24](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/aba3b796-49f5-4b59-9f98-a051059fc7ba)

Also, the description of battery buffer quest has some errors, since it says crafting **ANY** kind of battery buffer will finish this task, and I have crafted a 4x LV battery buffer, so the whole task must be unlocked.

### Actual Behavior

The chemical reactor quest cannot be done once I click it.

![2024-03-02_21 04 34](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/9588dce1-97cf-44f0-b7cd-edcf460e0592)

(Updated on 2024.03.04)

The LV battery quest cannot be finished either, even though all the damands are reached.

The LV battery buffer task just finished 1/3, not the whole task.

![58OJ1ZB9TSV~4@L~_POW){X](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/664d6f92-6e59-4399-bf01-1a8aaf56a814)

### Steps to Reproduce

1. Store the liquid rubber in the steel drum;
2. Open the FTB quest windows and find chemical reactor quest;
3. Click the "liquid rubber" icon.

(Updated on 2023.03.04)

1. Make a small sodium battery and finished canning machine task;
2. Open the FTB quest windows and find LV battery quest;
3. Click the "LV battery" icon.

### Additional Information

I have found that **at least the requiring condition of LV batteries is erred**. Similar errors may also appear in chemical reactor quest.  (See lv__low_voltage.snbt)

The quest file in ver. 0.6.15 wrote like

```
subtitle: "Chemistry for dummies"
tasks: [
	{
		id: "108424445D0F748A"
		item: "gtceu:lv_chemical_reactor"
		type: "item"
	}
	{
		amount: 1296L
		fluid: "gtceu:rubber"
		id: "75DD10F659BA5406"
		type: "fluid"
	}
]
title: "Basic Chemical Reactor"
# (blah blah blah)
subtitle: "Batteries for storing energy!"
tasks: [{
	icon: "gtceu:lv_sodium_battery"
	id: "47D0D12A26963702"
	item: {
		Count: 1b
		id: "itemfilters:tag"
		tag: {
			value: "forge:batteries/lv"
		}
	}
	title: "Any LV Battery"
	type: "item"
}]
title: "Batteries!"
```

However, for liquid rubber task, the fluid unit should be used as mB, not L (maybe L means "long" data type, I think, so this may not be a bug.), and submitting fluid should use quest detector or something else in FTB quest. For LV batteries quest, the tag of GTCEuM LV batteries wrotes "gtceu:batteries/lv", not "forge:batteries/lv"

**Comment by chemlzh** [comment]
@SpeeeDCraft @Xikaro The requiring conditions written in quest file have annoying problems, which will block us from completing the quests, therefore it would be better if you can figure it out. Thanks very much!

**Comment by SpeeeDCraft** [comment]
We know about that, but I havent time for now, to fix this, I need 1 or 2 weeks to fix my shit work

**Comment by chemlzh** [comment]
> We know about that, but I havent time for now, to fix this, I needs 1 or 2 weeks to fix my shit work, and then I will fix this

I see. I'll wait for your next update. Thanks again very much!
