### ISSUE TITLE
Не правильно работает заливка металла на сервере.

### ISSUE THREAD

**Issue by KoshakMineDEV** [TerraFirmaGreg-Team/Modpack-1.20.x#281]
### Версия модпака.

0.6.15

### Среда запуска

Сервер Forge

### Новые миры

Не уверен

### Ожидаемое поведение

В форму заливается 144mb металла и есть возможность достать предмет из формы.

### Фактическое поведение

В форму заливается 100mb металла, форма отображается как заполненная, предмет не достается.

### Действия по воспроизведению

Разогрел кусочки меди для отливки, залил в формы кирки и пилы, не смог дальше с ними работать.

**Comment by SpeeeDCraft** [comment]
Прикрепи ролик с проблемой

**Comment by QimBre** [comment]
Привет, Вот проблема с его сервера, два дня не можем отливку сделать)

![image2](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/89649548/9d6b501b-c58d-4c6f-85f5-114b3ea78439)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/89649548/f3e1021a-2e5e-4244-9545-d4f8ceb79e38)

**Comment by FlekGeKei** [comment]
У меня таже фигня, но только сам предмет (как пример медная головка топора) достаётся на секунду и возращается залитая форма без предмета.

**Comment by SpeeeDCraft** [comment]
Такое могло произойти при неправильной установке сборки, допустим вы на свой сервер не скопировали папку defaultconfigs из клиента модпака, поэтому у вас молды хранят 100mb. Я не могу воспроизвести у себя. Поэтому предположу, что проблема именно в конфигах, которые вы не скопировали.

**Comment by SpeeeDCraft** [comment]
Закрываю, потому что, у нас на сервере все прекрасно. Попробуйте переустановить сервер начисто или использовать тот, что на курсфордже мы публикуем.

**Comment by FlekGeKei** [comment]
Ну, у меня стоит Mohist
