### ISSUE TITLE
[Bug?] LV machine recycling recipes is not consistent with crafting recipes, causing red/blue steels turned into normal steel

### ISSUE THREAD

**Issue by chemlzh** [TerraFirmaGreg-Team/Modpack-1.20.x#282]
### Version modpack Used

0.6.15

### Environment

Singleplayer

### New Worlds

No

### Expected Behavior

LV machines are crafted with LV machine casings, which are made from red & blue steel plates. Therefore, when LV machines are recycled either by smelting in arc furnace, or by crushing in macerator, we will get red & blue steel products.

![2024-03-11_11 34 27](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/4286a6f2-600d-45db-b137-8c11e857942f)

### Actual Behavior

We will only get normal steel product from both kind of recylcing recipes, which is confirmed in EMI.

![2024-03-11_11 32 13](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/dc8d4ba9-97e1-4846-b62d-a1e7eaf0782e)

![2024-03-11_11 32 16](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/7589cc18-345a-45e2-acef-8b678b3a8de6)

### Steps to Reproduce

1) Put some LV machine either in arc furnace or macerator.

**Comment by SpeeeDCraft** [comment]
Thanks for report
