### ISSUE TITLE
Chainsaw Not Using Power When Cutting Trees.

### ISSUE THREAD

**Issue by BabBimmaBome** [TerraFirmaGreg-Team/Modpack-1.20.x#293]
### Version modpack Used

1.20.x.0.7.1

### Environment

Official Server

### New Worlds

Yes

### Expected Behavior

Chainsaw should be using power before durability.

### Actual Behavior

Chainsaw is using durability and not power. https://youtu.be/Lz6dIKFAvoU?si=sPwTew9ybulPA_0M

### Steps to Reproduce

Craft chainsaw try cutting any naturally generated tree.

### Additional Information

The chainsaw does consume power when cutting logs or any wood related block placed by the player.

**Comment by SpeeeDCraft** [comment]
https://github.com/GregTechCEu/GregTech-Modern/commit/422395cc632d8f2803c50e11e1cf5f94ece1ad2e fixed here

**Comment by SpeeeDCraft** [comment]
Fixed by GTCEu, I'm close this
