### ISSUE TITLE
Рыба и рыболовы. Рыбу ловить кайфово.

### ISSUE THREAD

**Issue by Tizer8** [TerraFirmaGreg-Team/Modpack-1.20.x#296]
### Версия модпака.

0.7.1

### Среда запуска

Сетевая, Одиночная.

### Новые миры

Да

### Ожидаемое поведение

Рыболов будет ловить рыбу пригодную для пищи и переработки, затрачивая на каждую ловлю по 1 нитке.

### Фактическое поведение

Ловится рыба из ваниллы, из которой только иглобрюх имеет пользу для переработки в жир и только такую. При этом не тратятся нитки.
![изображение_2024-03-21_185320065](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/161118906/e5d7d975-3d07-45ff-b8ce-3ad2889d80c7)

### Действия по воспроизведению

1. Ставим рыболов над бассейном.
2. Подаём питание. 
3. Закидываем ниток.
4. Получаем бесполезную рыбу.

### Дополнительная информация

Ещё было бы неплохо вернуть хлопок и кормить рыболов всеми тремя видами ниток. Шерстяные он принимать не хочет.

**Comment by SpeeeDCraft** [comment]
Fixed here: https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/commit/ada7fe088fa7d298427a7bcae8034fad9ba626c1

**Comment by SpeeeDCraft** [comment]
На счет ниток, тут все куда сложнее, возможно исправим это позже
