### ISSUE TITLE
Не плавится пыль голубой и красной стали в тигеле

### ISSUE THREAD

**Issue by HugeTeck** [TerraFirmaGreg-Team/Modpack-1.20.x#297]
### Версия модпака.

0.7.1

### Среда запуска

сервер Forge

### Новые миры

Нет

### Ожидаемое поведение

Раньше обе эти пыли плавились, но после обновы не стали

### Фактическое поведение

![изображение_2024-03-21_231641548](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/57455674/ace4831c-a53d-4fe6-9118-0e30718f77ba)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/57455674/091f7252-cbfe-4fe1-a4b3-95ad2d0b8b61)

### Действия по воспроизведению

После создания конкретной пыли в миксере не получается расплавить в тигеле

**Comment by HugeTeck** [comment]
Upd. 
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/57455674/7a30682c-bf7f-4f03-830e-fec8f1286371)
Не работает с какой либо другой пылью

**Comment by SpeeeDCraft** [comment]
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/52341158/18bef638-da18-470f-a319-4aa4d8a11df7)
Все плавится, чего ты обманываешь

**Comment by SpeeeDCraft** [comment]
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/52341158/a4c3eaf5-83ef-454f-b651-596dc79a34e4)
