### ISSUE TITLE
Etched 1.20.1 (Music discs)

### ISSUE THREAD

**Issue by Exzept1on** [TerraFirmaGreg-Team/Modpack-1.20.x#298]
### Version modpack Used

228

### Related Problem

-

### Your Solution

[etched](https://modrinth.com/mod/etched)

**Comment by FriendlyCube** [comment]
хм, а кто рецепты к нему делать будет

**Comment by SpeeeDCraft** [comment]
ты

**Comment by FriendlyCube** [comment]
жоско
