### ISSUE TITLE
Empty wooden form recipe Not working

### ISSUE THREAD

**Issue by IsiKuzmi** [TerraFirmaGreg-Team/Modpack-1.20.x#299]
### Version modpack Used

1.20.1   0.7.1  

### Environment

Server

### New Worlds

No

### Expected Behavior

When I try to create an empty wooden form, the recipe asks for any saw and any wood plank that the workbench would use to make an empty wooden form.

### Actual Behavior

When I try to create the empty wooden form, the recipe says any saw, and any wood plank. when I try to make it, it can only make a lumber...
Tested with copper, and wrouht iron saw, and TFC-oak, and douglas fir plank, Single player, and an own server...

### Steps to Reproduce

take any saw and any TFC plank.  Should work in principle....
![empty wooden form](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/164674433/3cfa1b85-ed28-4e0a-a530-2ec2cca0d556)

**Comment by 8oyNextDoor** [comment]
The current workaround is to craft lumber a few times and it'll allow you to craft a frame

**Comment by XyCrosier** [comment]
Another temporary workaround -- use bamboo planks, since they do not have a lumber recipe, it should work every time.

**Comment by KellyMiller103** [comment]
> The current workaround is to craft lumber a few times and it'll allow you to craft a frame

To be more specific: place a Saw and Plank (of any type) into the crafting grid, then swap the Plank out with a Plank of a different wood type. The output will change from Lumber to the expected Empty Wooden Frame.

**Comment by IsiKuzmi** [comment]
Thank you!
