### ISSUE TITLE
Food made with GregTech machine is rotten

### ISSUE THREAD

**Issue by JMmumu** [TerraFirmaGreg-Team/Modpack-1.20.x#303]
### Version modpack Used

0.7.2

### Environment

whatever

### New Worlds

Yes

### Expected Behavior

The food should be in the same state as the way TFC prepared

### Actual Behavior

Rotten!

### Steps to Reproduce

Made TFC(firmalife) food with the GregTech machine
![10FDB95716EE96F3F0B36A61195371C7](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/42163799/fb42969d-3b0b-4143-bdd2-cc6cbc693a3c)

**Comment by SpeeeDCraft** [comment]
I think it is impossible to fix this by simply changing something in the recipe, we will continue to look for a solution

**Comment by Exzept1on** [comment]
#295 dup
