### ISSUE TITLE
Два одинаковых, но разных типа воды

### ISSUE THREAD

**Issue by 8oyNextDoor** [TerraFirmaGreg-Team/Modpack-1.20.x#306]
### Версия модпака.

0.7.2

### Среда запуска

Любая

### Новые миры

Да

### Ожидаемое поведение

Наличие одного единого типа солёной воды

### Фактическое поведение

Солёная вода есть в двух формах - тфк и грега, они разные, имеют разные рецепты и не взаимозаменяемы

### Действия по воспроизведению

Глянуть рецепты, связанные с этими 2 версиями солёной воды, например:
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/130379681/d75120cd-9233-404a-95f1-69bf31b263a8)
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/130379681/7e5b8fce-5388-4f59-bd98-df6bab6f9ac9)

**Comment by FallenMind** [comment]
Поставь это в feature, а не баг. Как по мне - это морская и солёная вода, они разные

**Comment by SpeeeDCraft** [comment]
@FallenMind полностью прав, эта вода как и показано на скриншотах имеет разный рецепт декрафта, собсна это разная вода, в будущем думаю есть смысл переименовать тфк вариант в морскую

**Comment by Exzept1on** [comment]
Исправлено посредством переименовывания ТФК воды в морскую.
