### ISSUE TITLE
Macaw's All-In-One Mod request for TFC

### ISSUE THREAD

**Issue by Da1NOnlyCheezIt** [TerraFirmaGreg-Team/Modpack-1.20.x#307]
### Version modpack Used

0.7.2+

### Your Solution

Looking for previous requests, i found #39.
Will this mod be readded to the pack for 0.7.3+ or 0.8.0+? I see an old feature for this in russian but it looks like it was removed. For merge #132
It's been a few months since it was used in the pack it seems

### Additional Information

https://www.curseforge.com/minecraft/mc-mods/macaws-for-terrafirmacraft

**Comment by SpeeeDCraft** [comment]
Planned on 0.7.4
