### ISSUE TITLE
ae2 дороботка 

### ISSUE THREAD

**Issue by FriendlyCube** [TerraFirmaGreg-Team/Modpack-1.20.x#309]
### Версия модпака.

0.7.2

### Связанная проблема

надо обновляться!

### Ваше решение

добавим аддоны:
https://www.curseforge.com/minecraft/mc-mods/ae2-network-analyser
Олег сказал Олег сделал

https://www.curseforge.com/minecraft/mc-mods/ae2-insert-export-card

обоим модам поменять крафты

изменения в моде ае2:
возвращаем заряжатель и отрубаем в конфигах зарядку кристаллов, вероятно стоит написать в описании блока об этой админской шутке, так же возвращаем палку для заряжателя.
зачем? ответ:  фикс проблемы, которая заключается в том что предметы из ае2не возможно зарядить (если будет не лень(будет) напишу по поводу этого прикола исуе) фикс осуществляется появлением блока в котором можно заряжать ае2 предметы.

### Дополнительная информация

код в конфиге отвечающий за зарядку айтемов: 
"battery": {
    "chargerChargeRate_comment": "The chargers charging rate factor, which is applied to the charged items charge rate. 2 means it charges everything twice as fast. 0.5 half as fast.",
    "chargerChargeRate": 1.0,
    "wirelessTerminal": 1600000,
    "chargedStaff": 8000,
    "entropyManipulator": 200000,
    "portableCell": 20000,
    "colorApplicator": 20000,
    "matterCannon": 200000
  },

**Comment by SpeeeDCraft** [comment]
Закрыто здесь: https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/commit/bc2823c6368039fafd4b7c0d6a732e035d186420
На счет зарядки обсудим после
