### ISSUE TITLE
The game crashed whilst mouseclicked event handler

### ISSUE THREAD

**Issue by nerdError** [TerraFirmaGreg-Team/Modpack-1.20.x#311]
### Version modpack Used

0.7.2

### Environment

Singleplayer

### Side Crashed

Client

### New Worlds

Yes

### Steps to Reproduce

1) Start the game through CurseForge
2) Click "New game" button

### Crash Report
```mouseClicked event handler```
```java.lang.IllegalArgumentException: gtceu:smelt_poor_raw_fluorite_ore_to_ingot: output items is empty```

[Crash](https://pastebin.com/cp7dcFWr)
[Log](https://pastebin.com/hgmL75gG)

### Additional Information

I just downloaded the modpack with CurseForge, launched it and tried to start new game... And the game crashes. Tried to do it multiple times, it crashes consistently

**Comment by FriendlyCube** [comment]
try to remove the bobby mod

**Comment by SpeeeDCraft** [comment]
Weird, cant reproduce. closed
