### ISSUE TITLE
Краш при смене ресурспака

### ISSUE THREAD

**Issue by WIFIMAXXX** [TerraFirmaGreg-Team/Modpack-1.20.x#312]
### Версия модпака.

0.7.2

### Среда запуска

Одиночная игра

### С какой стороны краш

Клиент

### Новые миры

Не уверен

### Действия по воспроизведению

Открываем "Resource packs",  добавляем выбранные ресурспаки (я использовал от ILAORE), нажимаем "Done", нас переносит на окно настроек, еще раз нажимаем "Done" и игра вылетает

### Отчет о сбое

Ссылка на краш репорт и логи: https://gist.github.com/WIFIMAXXX/2a1f9f4e78f9a2ea3abf3e413c8ac46e

### Дополнительная информация

Вероятно об этом баге уже писали, но я такой темы не обнаружил, было бы классно, если бы в следующих версиях пофиксили

**Comment by SpeeeDCraft** [comment]
Ахах, ну переполнение стека, бывает че, мы бессильны, ждем апдейт от разрабов прекрасных модов.
Я кстати словить ошибку не могу, поэтому терпим
