### ISSUE TITLE
Can't place wrought iron sheet and can't cut down a whole tree

### ISSUE THREAD

**Issue by PRCairforce** [TerraFirmaGreg-Team/Modpack-1.20.x#315]
### Version modpack Used

0.7.2 and 0.7.1

### Environment

singleplayer and server

### New Worlds

Yes

### Expected Behavior

In TFC 1.18.2, I remenber that we need to place wrought iron sheet on the fire bircks to make a blast furnance, and we can cun down the whole tree by digging the bottom trunk.

### Actual Behavior

In TFG 0.7.2 and 0.7.1 (I mean, the game on my computer and my friends' computer are all these 2 version), we just can't put wrought iron sheet on the fire bricks (Lshift+right click), and we can't cut down the whole tree by digging only one block (instead, its behavior is more like cutting trees in the original version of mc). Also, our games (clients,not server) sometimes gets stuck when we are playing in our server. By the way, these characteristics are all we found. We are not sure if there are any other bugs.

### Steps to Reproduce

On our computers, reproduce these bugs only need us to install TFG 0.7.2 or 0.7.1 by HMCL, and create a new world.

### Additional Information

I've not heard anyone else trigger this bug except me and my friends. However, one of my schoolmate said that TFG 0.7.2 on his computer is normal. His TFG is update from earlier versions. He use HMCL to install TFG and run through official launcher.

**Comment by PRCairforce** [comment]
I‘ve tried to install TFG 0.7.2 by the mmcpack on github, but something more strange happend. When I create a world in creative mode, or I tried to use "/give" or "/gamemode", all the bugs survived, and instead, when I create a new word in survival mode and turn down the cheating mode, I can cut down trees normally, but I can't place wrought iron sheet as well.

**Comment by PRCairforce** [comment]
Finally... I found that all the bugs are from firmacivilization and KubeJS (startuo.scripts failed to load successfully)... The solution is that delete firmaciv in KubeJS.

**Comment by SpeeeDCraft** [comment]
wait, stop, its bad way to fix issue, and I cant reproduce this, keep this open for now..

**Comment by PRCairforce** [comment]
Well, I'd be happy to provide more details. The core reason of these bug is KubeJS failed to load successfully.For example, I remenber that in TFG, tools made through TFC ways will be changed to GTCeu version by default, and these configuration files are saved in KubeJS. So once KubeJS can't load properly, all the things will get wrong. The stone axe is no longer GT version, but TFC version (idk why TFC axes can't cut down a whole tree by once). The kubeJS on my computer failed to load everytime (because of firmaciv, but idk what is going wrong with this mod). After I delete files about firmaciv (files in KubeJS and the mod itself), all problems have been solved.

**Comment by SpeeeDCraft** [comment]
shit magic again :p

**Comment by PRCairforce** [comment]
But anyway, although there are still some doubts, I can at least play normally now. (By the way, TFG is so cool)

**Comment by PRCairforce** [comment]
(To reproduce this bug, maybe you can just delete one of these mods, such as firmaciv, so that KubeJS can't load properly because it can't find the mod.)

**Comment by PRCairforce** [comment]
Wait, I have another question. Why when I play in my TFG server, I always stuck (about twice an hour), but it won't happen in singleplayer

**Comment by SpeeeDCraft** [comment]
What is your system? windows or unix-based any system? And can you provide some logs when you cant cut down trees and when you cant place any sheet to ground? :)

**Comment by PRCairforce** [comment]
Let me see...
My operating system is Windows11 23H2 22631.3007
and here is a log when these things still happen
[2024-04-03-4.log.gz](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/files/15109709/2024-04-03-4.log.gz)

**Comment by PRCairforce** [comment]
Actually I think it's not a TFG bug, just because the mod firmaciv on my computer happened to some unknown error...
