### ISSUE TITLE
Добавить мод на доп декор

### ISSUE THREAD

**Issue by 8oyNextDoor** [TerraFirmaGreg-Team/Modpack-1.20.x#318]
### Версия модпака.

0.7.2

### Ваше решение

https://www.curseforge.com/minecraft/mc-mods/framedblocks можно добавить вот этот хороший моdick

**Comment by FriendlyCube** [comment]
Мод который добавляет больше возможностей для декора базы

**Comment by SpeeeDCraft** [comment]
Добавлен в 0.7.3
