### ISSUE TITLE
[Bug] Titanium fluid cells turn into tungstensteel when recycled by arc furnace or macerator

### ISSUE THREAD

**Issue by chemlzh** [TerraFirmaGreg-Team/Modpack-1.20.x#319]
### Version modpack Used

0.7.2

### Environment

Singleplayer

### New Worlds

No

### Expected Behavior

Titanium fluid cells should be turned into 6 titanium ingots per item.

Titanium fluid cells should be crashed into 6 titanium dusts per item.

### Actual Behavior

Titanium fluid cells are transformed into 6 tungstensteel ingots per item.

Titanium fluid cells are crashed into 6 tungstensteel dusts per item.

### Steps to Reproduce

Put titanium fluid cells in the arc furnace with enough oxygen, or crashed in the macerator.

### Additional Information

This bug was also reported on GregtechCEu Modern. See https://github.com/GregTechCEu/GregTech-Modern/issues/1068

I have discussed with other players, and they told me that GTCEuM recipes are generated by automated programs. Therefore I doubt that something wrong may occurred in your kubeJS (or something else?)

**Comment by SpeeeDCraft** [comment]
funny gtceu :trollface:

**Comment by chemlzh** [comment]
It has been confirmed that this bug is induced by just GTCEuM, not made by your recipes, since game with pure GTCEuM and EMI still retains titanium-cell-to-tungstensteel recipes.

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/a012ff09-d43a-4048-a96b-eaaf40013be9)

**Comment by chemlzh** [comment]
Wiil be fixed in GTM future version. I have pushed the patch.

https://github.com/GregTechCEu/GregTech-Modern/pull/1169

**Comment by Exzept1on** [comment]
Gj
