### ISSUE TITLE
[Request for update] GTCEuM and AE2 upgrades, with quests of Research System (for GTCEuM) and Resonance Generator (for AE2) added

### ISSUE THREAD

**Issue by chemlzh** [TerraFirmaGreg-Team/Modpack-1.20.x#320]
### Version modpack Used

0.7.2

### Related Problem

GTCEuM has been upgraded to 1.2.0.a, featuring new Research System from original GTCEu, which is crucial for higher-tier electronic component.

AE2 has been upgraded to 15.1.1, which added a passive energy generation device called Crystal Resonance Generator.

Neither these features nor related quests have been introduced into the pack.

### Your Solution

1. Added GTCEuM 1.2.0.a  and AE2 15.1.1 (or higher if newer versions are released);
2. Implementing requests for new Research System and Crystal Resonance Generator.

**Comment by SpeeeDCraft** [comment]
yes, yes, yes, we are aware of these updates, but the tfg modpack update is getting big, so we will have to wait a while

**Comment by chemlzh** [comment]
I'm so sorry for bothering you so harshly. This pack does have too many features to be upgraded, and it's really a hard job. Thank you for your amazing modpack! @SpeeeDCraft
