### ISSUE TITLE
[Bug] Poor raw ore has higher crushed ore production than normal/rich ores

### ISSUE THREAD

**Issue by chemlzh** [TerraFirmaGreg-Team/Modpack-1.20.x#321]
### Version modpack Used

0.7.2

### Environment

Singleplayer

### New Worlds

No

### Expected Behavior

Poor ores that can be crushed into more than 1 crushed ore (main product) should gain only 1-3 additional ore(s) with a probability.

### Actual Behavior

Poor ores that can be crushed into more than 1 crushed ore (main product) gain additional ores that are 1-3 times equal to main products with a probability, thus making normal/rich ores production relatively decreased.

### Steps to Reproduce

Put the poor ores into the macerator with voltage no lower than HV. The poor ores must be crushed into more than 1 crushed ore in macerator with MV-or-lower voltage.

### Additional Information

Since I'm not familiar with GTM, I wrongly put this issue on GTM. After contacted with GTM team, I realized that it's the modpack that cause this bug. So I repost this issue here.

https://github.com/GregTechCEu/GregTech-Modern/issues/1118

**Comment by SpeeeDCraft** [comment]
Thanks for report

**Comment by SpeeeDCraft** [comment]
Fixed in dev
