### ISSUE TITLE
Create: Destroy submod

### ISSUE THREAD

**Issue by dertruffel** [TerraFirmaGreg-Team/Modpack-1.20.x#329]
### Version modpack Used

0.7.2

### Your Solution

https://www.curseforge.com/minecraft/mc-mods/create-destroy
Submod for Create that brings more chemistry

**Comment by Jayx20** [comment]
I disagree with adding Destroy, gregtech already adds chemistry and they likely conflict massively.

**Comment by SpeeeDCraft** [comment]
Nope, we have GTCEu for that
