### ISSUE TITLE
TerraFirmaShips and Macaw

### ISSUE THREAD

**Issue by dertruffel** [TerraFirmaGreg-Team/Modpack-1.20.x#330]
### Version modpack Used

0.7.2

### Your Solution

https://www.curseforge.com/minecraft/mc-mods/terrafirmaships
https://www.curseforge.com/minecraft/mc-mods/macaws-for-terrafirmacraft
I believe these would be a good addition to the pack, compatibility should be already done as its compat mods.

**Comment by SpeeeDCraft** [comment]
TFC Ships rejected because we have FirmaCiv. Macaws will be added in next updates, like 0.7.4 or 0.7.5
