### ISSUE TITLE
[Bug] GT spared parts can be molten at least twice as much as GT in TFC crucible

### ISSUE THREAD

**Issue by chemlzh** [TerraFirmaGreg-Team/Modpack-1.20.x#336]
### Version modpack Used

0.7.2

### Environment

Singleplayer

### New Worlds

No

### Expected Behavior

GT has configured that 1 bolt equals to 18mB liquid/molten metal, 1 screw equals to 16mB liquid/molten metal, and 1 ring equals to 36mB liquid/molten metal.

### Actual Behavior

1 bolt can be molten into 36mB liquid/molten metal, 1 screw equals to 72mB liquid/molten metal, and 1 ring equals to 72mB liquid/molten metal.

### Steps to Reproduce

For spared part errors:

1. Put a metal ingot and bolt mold in the extruder, and we'll get 8 bolts;
2. Put bolts in the TFC crucible and heating.

Noted that ingots should be able to be molten in TFC.

### Additional Information

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/eb84c9f3-f8e2-486f-8fce-fedd63b99ad6)

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/f7aca70a-496d-4dac-aa62-37b17a715fbb)

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/a206fcbe-3119-4978-89e1-9ead848bb186)

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/449fc4d9-e4cf-41f7-a985-21ccee8cc798)

**Comment by chemlzh** [comment]
#334 I have figured it out, could you help me merge the code? @SpeeeDCraft

**Comment by Exzept1on** [comment]
Fixed
