### ISSUE TITLE
After disabeling TFC book you cannot preview multiblock structures

### ISSUE THREAD

**Issue by joelimgu** [TerraFirmaGreg-Team/Modpack-1.20.x#338]
### Version modpack Used

0.7.4

### Environment

Singleplayer

### New Worlds

Yes

### Expected Behavior

Even if some pages of the TFC book were wrong, previewing multi-block structures was really helpful. I would expect to have a way to continue doing that either with those entries enabled on the book or some other way.

### Actual Behavior

TFC book disabled so unable to see the preview.

### Steps to Reproduce

In the 0.7.2 open a multiblock index in TFC book and press on the little eye to preview the multiblock structure. In 0.7.4 those indexes are disabled.

### Additional Information

This is caused by the TFC book being disabled. I understand the reason why it has been disabled but instead of disabling it I think it should be left enabled until all the functionality and documentation has been migrated elsewhere.

**Comment by Exzept1on** [comment]
Suffer

**Comment by Bahnschrift** [comment]
Removing the book has also removed the option to see the required growing / spawning conditions for crops. If there's a plan to add this information to quests later, it really seems like it would be a better option to leave the book enabled until that information is actually added, even if some of the other information is misleading.

**Comment by dertruffel** [comment]
How can we reenable the book?

**Comment by Exzept1on** [comment]
minecraft_instance/config/tfc-client.toml -> showGuideBookTabInInventory = true

**Comment by Exzept1on** [comment]
funny, but this is already true, wtf..

**Comment by dertruffel** [comment]
The guidebook is empty, im 99% sure terrafirmagreg-core disables the content, but tfg-core is closed source as far as im aware?

**Comment by Exzept1on** [comment]
what? tfg-core do nothing with guidebook
