### ISSUE TITLE
Tool tag-mismatches (Axes can no longer strip logs)

### ISSUE THREAD

**Issue by FridgeBoy95** [TerraFirmaGreg-Team/Modpack-1.20.x#340]
### Version modpack Used

0.7.4

### Environment

Singleplayer & Multiplayer

### New Worlds

Yes

### Expected Behavior

As you can see from those screenshots these are the tags that an axe and a saw should have respectively.
These screenshots were taken on the 0.7.2 version of the pack

![2024-05-01_14-59-17](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/168646893/6592b47a-02ce-4b42-9c5d-27a3b2d3297e)

![grafik](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/168646893/4c13fd6e-343a-4a1e-b035-6ed1d8967e83)

### Actual Behavior

In the 0.7.4 version you can see that the tags no longer are the same as previously.
This leads to Axes no longer being able to strip logs, and saws coincidently not able to make canoes from stripped logs, but axes capable of that.

I have not checked the other tools, they might be affected aswell.

![2024-05-01_14-54-33](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/168646893/b5badf92-693b-4209-85eb-292ff5893289)

![javaw_2024-05-01_14-54-48](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/168646893/8a844261-c35b-4dbc-bda1-d5355b48b287)

### Steps to Reproduce

update to 0.7.4

### Additional Information

As of writing this 0.7.5 just released, issue not mentioned in changelog and I am currently not able to verify if it was fixed coincidentally.

**Comment by FridgeBoy95** [comment]
Can now confirm.
Issue still persistent in 0.7.5

**Comment by Exzept1on** [comment]
blyat

**Comment by Exzept1on** [comment]
Fixed
