### ISSUE TITLE
Objects drop

### ISSUE THREAD

**Issue by somebody2506** [TerraFirmaGreg-Team/Modpack-1.20.x#341]
### Version modpack Used

0.7.5

### Environment

LAN

### New Worlds

No

### Expected Behavior

nothing special

### Actual Behavior

If you walk on objects lying on the floor, with a small chance they will break and drop
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/80541259/39cf54c0-61cc-4bfc-8fe7-4b9285ae65e3)

### Steps to Reproduce

i did nothing lol

### Additional Information

I think it's because of the mod that is responsible for the missing grass underfoot. But sometimes the grass disappears and the items are still lying

**Comment by Exzept1on** [comment]
Thanks for report

**Comment by Exzept1on** [comment]
Fixed
