### ISSUE TITLE
Create gated behind Steam & Steel (missing recipe?) or Progression changes not properly reflected within questbook

### ISSUE THREAD

**Issue by FridgeBoy95** [TerraFirmaGreg-Team/Modpack-1.20.x#344]
### Version modpack Used

0.7.3 and up

### Environment

Singleplayer & Multiplayer

### New Worlds

Yes

### Expected Behavior

Looking at the quests I'd expect Create to be gated behind gettign wrought iron and a coke oven which can both be acquired during the primitive age.
![grafik](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/168646893/a9ba5153-e9f3-4008-a55d-30efdfdb9fad)

### Actual Behavior

The only crafting recipe available for "gtceu:treated_wood_plate" required to make the cogs is currently gated strictly behind steam age and in turn, due to a lack of low pressure machines also gated behind steel.

![grafik](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/168646893/a7a60bb1-5d6e-41d0-9136-0e7f6d37b337)

### Steps to Reproduce

---

### Additional Information

This might not actually be a bug, but from the perspective of earlier versions create is as of now distinctly later available.

Either there is a missing recipe that would be available in the primite age to get "gtceu:treated_wood_plate" from "gtceu:treated_wood_plank".
or the "the beginning of Create" quest would need to be a dependent of the quest "Steel Ingot" instead of "Wrought Iron Ingot".

Before 0.7.3 This was not an issue as cogs could be made with a wooden gear, which just required any wrench and sticks.
![grafik](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/168646893/73a7f9ce-54c3-475f-8ea3-4f0f8693da3d)

**Comment by Exzept1on** [comment]
Result: Quests fixes. Thanks for report.
