### ISSUE TITLE
[Bug] Any tool head that has no TFC counterpart cannot crafted into tool

### ISSUE THREAD

**Issue by chemlzh** [TerraFirmaGreg-Team/Modpack-1.20.x#345]
### Version modpack Used

0.7.7

### Environment

Singleplayer

### New Worlds

No

### Expected Behavior

Spade head & stick can be used to craft spade.

(Update) Any tool head can be used to craft tool with a stick.

### Actual Behavior

Spade head & stick cannot be used to craft spade. Instead, the original GTM crafting method still remains.

(Update) Any tool head that has no TFC counterpart cannot crafted into tool with a stick. Instead, the original GTM crafting method still remains.

### Steps to Reproduce

1. Extrude a spade head with 2 ingots.
2. Try to craft spade with a spade head and a stick.

This also suits with other tool head that has no TFC counterpart (except for mining hammer).

### Additional Information

Original GTM crafting recipe for spade ramains.

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/2f8dd061-b240-49db-ae06-b81feef5f7ff)

Spade head has no use as for version 0.7.7.

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/989fff2d-b8c4-4bb7-83a2-763d0c304e35)

And could you please tell me where the crafting recipe with toolhead is? I'll try to fix it.

(Update) Butchery knife head cannot be crafted into butchery knife.

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/25cc2052-269e-47e5-a6e9-836baf028bf9)

Screwdriver tip can only be crafted into electronic screwdriver. Non-electronic screwdriver cannot be crafted.

![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/f63c2a71-3dc3-427e-9a10-4e17b25842a7)

I have found that whether toolhead to tool recipes exist is defined by code below (in kubejs\server_scripts\gregtech\recipes.js)

```javascript
    GTMaterialRegistry.getRegisteredMaterials().forEach(material => {
        //#region Рецепты инструментов
        
        if (material.hasFlag(TFGMaterialFlags.HAS_TFC_TOOL)) {
            global.GTCEU_ANVIL_TOOL_TYPES.forEach(toolType => {
                let toolStack = ToolHelper.get(toolType, material)

                event.recipes.tfc.advanced_shaped_crafting(TFC.itemStackProvider.of(toolStack).copyForgingBonus(), [
                    'A',
                    'B'
                ], {
                    A: `gtceu:${material.getName()}_${toolType.name}_head`,
                    B: '#forge:rods/wooden'
                }, 0, 0).id(`gtceu:shaped/${toolType.name}_${material.getName()}`)
    
            })
        }
```

It seems that TFGMaterialFlags has not included butchery head, screwdriver and spade. However, I cannot edit TFG-core, so I have to seek help from you. @Exzept1on @Xikaro

**Comment by Exzept1on** [comment]
Fixed, but screwdrivers, ohhhhh, its gtceu bug.
