### ISSUE TITLE
Glasswork using a blow pipe is impossible

### ISSUE THREAD

**Issue by nullTheCoder** [TerraFirmaGreg-Team/Modpack-1.20.x#347]
### Version modpack Used

0.7.7

### Environment

Forge Server

### New Worlds

Yes

### Expected Behavior

When holding a blow pipe which is hot enough to have work done on it, you should be able to hold it without it dropping so that it was possible to use other instruments.

### Actual Behavior

When you pick up a glass blowing pipe after warming it up, it drops due to it being too hot. You can't do most glasswork recipes due to being unable to hold an item in off-hand

### Steps to Reproduce

1. heat up a blow pipe with glass on it
2. pick up that blow pipe
3. exit the menu of the coal pit
4. the blow pipe drops unless you hold tongs
5. if you hold the tongs, you can't use the blow pipe since it

**Comment by Exzept1on** [comment]
Fuck. Thanks for report

**Comment by SakuraRK** [comment]
I want try to delete the "hot or not" to temporary fix it.

**Comment by theSignSaysDie** [comment]
I'm not well-acquainted with the mechanics of the mod, but surely it'd be easier to simply make a whitelist of items and tags for which the Hot or Not mechanics are not processed?

**Comment by BabBimmaBome** [comment]
> I'm not well-acquainted with the mechanics of the mod, but surely it'd be easier to simply make a whitelist of items and tags for which the Hot or Not mechanics are not processed?

there is no config for this so the original mod dev would have add it. Which i guess is why exception called him a shit dev xd

**Comment by Exzept1on** [comment]
There is a blacklist, but there is no white list, why? ask the author of the mod, actually it has already been fixed by some crutch, until the mod developer fixes it himself

From dev:
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/52341158/95a70f4e-1a07-44c6-8ef0-5794a9435121)

**Comment by Exzept1on** [comment]
10 days, and no fix, so fucking cool

**Comment by theSignSaysDie** [comment]
> 10 days, and no fix, so fucking cool

Development takes time and I'm certain they're not being paid to keep this mod working. Cut them some slack.

**Comment by kotyarakot** [comment]
> There is a blacklist, but there is no white list, why? ask the author of the mod, actually it has already been fixed by some crutch, until the mod developer fixes it himself
> 
> From dev: ![image](https://private-user-images.githubusercontent.com/52341158/332863196-95a70f4e-1a07-44c6-8ef0-5794a9435121.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3Mzc5NjEsIm5iZiI6MTcxNjczNzY2MSwicGF0aCI6Ii81MjM0MTE1OC8zMzI4NjMxOTYtOTVhNzBmNGUtMWEwNy00NGM2LThlZjAtNTc5NGE5NDM1MTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI2VDE1MzQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3YjZlMjNiY2VmZjA2ZWM4MDM0YzhhYzk1NTc1OTkzZDUwNGM5ZDMwNWE3NWI2ZmJkMDg1OTcwNjlkMTA1NTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rP_mmwgTSc_EVObymwBJ3F45kfmaTxtqY7y_MxRDdZg)

How to do it? Is there any command in the game or i need to change it somewhere else?

**Comment by Exzept1on** [comment]
You just need to upgrade to 0.7.9
