### ISSUE TITLE
Intranet Penetration Failed

### ISSUE THREAD

**Issue by lunareclipse-64** [TerraFirmaGreg-Team/Modpack-1.20.x#348]
### Your Question

**Version modpack Used**
0.7.7

I've tried to play TFG 0.7.7 with my friend through intranet penetration, but failed.
It's not the same as the 1.12.2 version TFG and other 1.20.1 modpacks, our intranet penetration works when playing these packs.
I did more tests, found that multiplayer through LAN is working well, so maybe there is a mod or something blocking the intranet penetration? By the way, VLAN(Zerotier) also failed.
When the joiner started loading chunks they'll be disconnected by "Connection Reset".
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/61282200/097c573c-19b5-4103-8072-1910c007558c)
And here's the relative log in lastest.log:
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/61282200/3bbaa621-e6d3-4199-be14-7e1ce3ddc9ac)
Sorry I submitted the same question to the 1.12 repository.

**Comment by Exzept1on** [comment]
Try other modpacks on 1.20, or vanilla, because all works for for us. You is first person who reported bug like that

**Comment by lunareclipse-64** [comment]
> Try other modpacks on 1.20, or vanilla, because all works fine for us. You is first person who reported bug like that

I've tried other 1.20.1 packs such as Prominence II, and vanilla as well hours ago. They are all normal, but TFG 0.7.2~0.7.7 still can't.
I also tried former edition 0.6.14, even through LAN I can't get into multiplayer.

**Comment by Exzept1on** [comment]
Strange. Can u send ur log, client and server please

**Comment by lunareclipse-64** [comment]
These are the logs of **successful** example through LAN (12:49~12:51) in TFG 0.7.7, both are offline accounts:
Server(Huai_123):
[latest.log](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/files/15211811/latest.log)
Client(Seleclipse):
[latest.log](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/files/15211812/latest.log)

**Comment by lunareclipse-64** [comment]
And these are the logs of **failed** example through Intranet Penetration(12:59:33~12:59:58) in TFG 0.7.7, Server is offline, Client is Microsoft account.
The Intranet Penetration server is Cpolar, which works well in Vanilla instance hours ago. I've used this for about 10 different packs in different minecraft versions.
Server(Huai_123):
[latest.log](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/files/15211825/latest.log)
Client(Seleclipse):
[latest.log](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/files/15211826/latest.log)
And still comes with "Connection Reset".

**Comment by Exzept1on** [comment]
id what is going on, any way, working fine on my machine, with my friend on 0.7.8.
