### ISSUE TITLE
Невозможно сделать блок шерсти на ткацком станке - конфликт рецептов ткацкого станка

### ISSUE THREAD

**Issue by aiko135** [TerraFirmaGreg-Team/Modpack-1.20.x#354]
### Версия модпака.

Последняя

### Среда запуска

Игра на сервере

### Новые миры

Да

### Ожидаемое поведение

Ожидается что можно сделать блок шерсти из 4 шерстяной ткани на ткацком станке

### Фактическое поведение

Рецепт из 4 шерстяной ткани не работает, вместо этого ткацкий станок предлагает рецепт из 2 шерстяной ткани крафт шерстяной руковицы

### Действия по воспроизведению

1.Поставить ткацкий станок 2. Взять в руку 4 шерстяной ткани 3. Поместить ткань на ткацкий станок 4. Конфликт рецептов

**Comment by Exzept1on** [comment]
Дубликат: https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/issues/351
