### ISSUE TITLE
Can't make Tin Alloy

### ISSUE THREAD

**Issue by FiveSixEP** [TerraFirmaGreg-Team/Modpack-1.20.x#356]
### Version modpack Used

0.7.6

### Environment

Forge Server

### New Worlds

Yes

### Expected Behavior

Expected to be able to melt #iron and tin to get tin alloy

### Actual Behavior

Blast furnace makes liquid pig alloy which is not suitable.
Alloy smelter is not able to be made without rubber sheets which is not obtainable without LV

### Steps to Reproduce

Check tin alloy recipe chain

**Comment by BabBimmaBome** [comment]
lol

**Comment by BabBimmaBome** [comment]
bro put 1 wrought iron ingot and 1 tin ingot in a crucible xd

**Comment by FiveSixEP** [comment]
Wrought iron can't melt in a crucible because it needs Brilliant White

**Comment by BabBimmaBome** [comment]
so use your bellows...

**Comment by FiveSixEP** [comment]
Thank you, I didn't know that worked, the guide book isn't working and google searches didnt work
