### ISSUE TITLE
[Bug] Processing array task is broken, and AE2 creative energy cell cannot be crafted

### ISSUE THREAD

**Issue by chemlzh** [TerraFirmaGreg-Team/Modpack-1.20.x#360]
### Version modpack Used

0.7.8 (may exist in 0.7.3+)

### Environment

Singleplayer

### New Worlds

No

### Expected Behavior

After GTM 1.2.0.a, processing array is totally banned, since GCyM machines are implemented. And related tasks should be deleted. (Tested on TFG 0.7.8+GTM 1.2.1)

AE2 creative energy cell cannot be crafted in survival mode. It needs an assembly line crafting recipe, in which a gravi star is consumed.

### Actual Behavior

Processing array task still exists, however it cannot be finished, since requirement is broken.

No crafting recipe is found for AE2 creative energy cell.

### Steps to Reproduce

Open FTB tasks, you will find requirement of processing array task is null.

Put mouse on AE2 creative energy cell, and press "R" to try to open EMI interface.

### Additional Information

![2024-05-13_09 00 30](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/de1aae3c-35ad-467b-bf00-99cfa6747592)

![2024-05-13_09 09 53](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/32123043/3501db8d-f791-4b85-a539-1bbf0d71aef6)

**Comment by Exzept1on** [comment]
What? fixed in 0.7.9
