### ISSUE TITLE
Апгрейды на рюкзаки из мода "Sophisticated Backpacks" можно скрафтить лишь используя кожу животных

### ISSUE THREAD

**Issue by mora-unie-youer** [TerraFirmaGreg-Team/Modpack-1.20.x#363]
### Версия модпака.

0.7.8

### Среда запуска

одиночная игра, игра по локальной сити

### Новые миры

Да

### Ожидаемое поведение

Для крафта основы апгрейдов должна использоваться кожа как животного происхождения, так и ананасовая

### Фактическое поведение

Для крафта можно использовать только животную кожу
![image](https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/assets/96782282/4b507ae7-0b30-4d45-a3d5-f593864bd6bd)

### Действия по воспроизведению

1) Посмотреть крафт предмета `sophisticatedbackpacks:upgrade_base`

**Comment by Exzept1on** [comment]
Вот так то лучше, а то пингуют меня там, поправим, благодарим за инфу.
