### ISSUE TITLE
Upgrade Ksyxis to 1.3.0

### ISSUE THREAD

**Issue by Treazul** [TerraFirmaGreg-Team/Modpack-1.20.x#366]
### Version modpack Used

0.7.8

### Your Solution

Upgrade Ksyxis to 1.3.0 

### Additional Information

1.2.2 is being marked as a virus by a number of scanners, as per https://www.virustotal.com/gui/file/8e97bb392718099d54377738a3501284eef98fbd54f6b46b4350fc9267ef4d47 - This stops the modpack from even being installed.

**Comment by BabBimmaBome** [comment]
works on my machine

**Comment by Exzept1on** [comment]
lol, thanks for report

**Comment by Exzept1on** [comment]
Fixed on 0.7.9
