### ISSUE TITLE
Quests are not being completed when items required items are present

### ISSUE THREAD

**Issue by alekthehero** [TerraFirmaGreg-Team/Modpack-1.20.x#372]
### Version modpack Used

1.20.x.0.7.9

### Environment

Forge Server

### New Worlds

Unsure

### Expected Behavior

Quests are expected to be completed when required items are present in the player inventory.

### Actual Behavior

Quests are either not completing at all or the item needs to be in the player inventory for a long period of time for the quests to register and notify as complete.

### Steps to Reproduce

We have two FTB teams each with 2 players each.

1) Create an FTB team
2) Invite another player
3) Attempt to complete quests that require items
4) Wait and see how long it takes to register

Sometimes it will not register or take a while or be totally fine.

### Additional Information

It feels like FTB quests is lagging? or just not checking every tick for items in the player inventory.

**Comment by BabBimmaBome** [comment]
ever since 0.7.9

**Comment by alekthehero** [comment]
Seems to be related to teams, had my friend leave his team and join my team then leave my team and rejoin his team and it started working for now.

**Comment by caelansimms** [comment]
I can confirm, I have this same problem too. I am in a Singleplayer world.

**Comment by Fatilon** [comment]
I have this issue too, it takes awfully long time. To solve this I just throw some other things out of my inventory to register required items for quest

**Comment by Exzept1on** [comment]
Try to remove FTBQuestsOptimizer, and report the result

**Comment by meatmobile** [comment]
Still experiencing this even on 0.9.9
