### ISSUE TITLE
Add Farmer's Delight TFC

### ISSUE THREAD

**Issue by Lollovader** [TerraFirmaGreg-Team/Modpack-1.20.x#375]
### Version modpack Used

0.7.8

### Related Problem

This mod would just improve the slice of life aspect of TFC by adding more foods, so its not a necessary feature but it would be nice to see

### Your Solution

Adding the mod to the pack

**Comment by BabBimmaBome** [comment]
last updated jan 26th already looks abandoned

**Comment by FriendlyCube** [comment]
https://github.com/TerraFirmaGreg-Team/Modpack-1.20.x/issues/155#issuecomment-1873340976
