### ISSUE TITLE
server no workie

### ISSUE THREAD

**Issue by Cmonster820** [TerraFirmaGreg-Team/Modpack-1.20.x#385]
### Version modpack Used

0.7.12

### Environment

server launch

### Side Crashed

Server

### New Worlds

Unsure

### Steps to Reproduce

I tried to launch the server on exaroton and it didnt work

### Crash Report

https://mclo.gs/LGeBTS8

**Comment by WaterMelwin** [comment]
Start NeoForge 20.6.111-beta Server

**Comment by Cmonster820** [comment]
???
only jar file is the minecraft_server one

**Comment by WaterMelwin** [comment]
wow thats the one you use!

**Comment by Cmonster820** [comment]
I don't know what you mean then

**Comment by Exzept1on** [comment]
Some mods which contain TFG not compatible with NeoForge, use ordinary Forge.
