### ISSUE TITLE
Manual Recipe for Thin Rubber Sheets

### ISSUE THREAD

**Issue by ArcWielder** [TerraFirmaGreg-Team/Modpack-1.20.x#390]
### Version modpack Used

0.7.12

### Related Problem

Create mod funnels require Thin Rubber Sheets which are locked behind LV machinery. 

### Your Solution

Add a manual recipe (similar to making metal foil) for rubber where you craft 1 Rubber Plate and a hammer together to get 2 Thin Rubber Sheets.

**Comment by WaterMelwin** [comment]
yep

**Comment by WaterMelwin** [comment]
whats the issue

**Comment by ArcWielder** [comment]
It means that part of create (which is considered ULV) is locked behind LV machinery, but I suppose you could just use chutes instead of funnels.

**Comment by WaterMelwin** [comment]
wow how its supposed to be

**Comment by ArcWielder** [comment]
rude

**Comment by WaterMelwin** [comment]
lol
