### ISSUE TITLE
Не работает рецепт покраски рюкзаков SophisticatedBackpacks

### ISSUE THREAD

**Issue by So0vey** [TerraFirmaGreg-Team/Modpack-1.20.x#79]
### Вы используете последнюю доступную версию?

Yes

### Среда запуска

официальный сервер

### Новые миры

Да

### Ожидаемое поведение

Хочу розовый портфельчик

### Фактическое поведение

Крафт цветных рюкзаков есть, но ни на верстаке, ни в инвентаре не крафтится

### Действия по воспроизведению

Сделан рюкзак, сделан краситель, не крафтится, даже в бочке с краской замочить нельзя

**Comment by FriendlyCube** [comment]
больше инфы:

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/112543401/f4b52c27-b938-4e4b-ad7e-2d3c71b49b89)

![image](https://github.com/TerraFirmaGreg-Team/TFG-Modpack-1.20.x/assets/112543401/7eef98e5-f735-4e3f-a715-6f2df7a3df32)

**Comment by SpeeeDCraft** [comment]
Баг мода на рюкзаки, при чем я не могу их удалить или заменить, а добавлять свои, там будет кривая механика, когда при изменение цвета рюкзак будет терять все вещи, короче ждем пока разраб вспомнит.

https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/914

**Comment by SpeeeDCraft** [comment]
Удалены рецепты с этим прекрасным чудом
